import * as THREE from '../../rail-3d/vendor/three.module.js';
import {loadGarageModel,createConsist,loadGarageParts} from '../../rail-3d/garage-model.js?revision=doors-0924';
import {createTerrainFollower} from '../../rail-3d/garage-scenes/consist-3d.js';
const kind=document.body.dataset.scene,canvas=document.querySelector('#scene'),loading=document.querySelector('#loading'),select=document.querySelector('#train'),reduced=matchMedia('(prefers-reduced-motion: reduce)'),speed=2.6;
const hours=Number(new Intl.DateTimeFormat('en',{timeZone:'Asia/Taipei',hour:'numeric',hourCycle:'h23'}).format(new Date()));
let period=hours<5||hours>=19?'night':hours<7?'dawn':hours>=17?'sunset':'day',time=kind==='duoliang'?8:0,view=matchMedia('(max-width:800px)').matches?'train':'world',zoom=1,yaw=-1.12,elevation=.61,span=30,raf=0,last=0,running=!reduced.matches,disposed=false,ready=false,changing=false,trainShown=true,serial=0,controller,train,primary,follower,opposing,opposingFollower,place,visitorKits,renderer,env,draws=0,model=select.value=document.body.dataset.default;
const distanceAt=t=>((t*speed-30+90)%180+180)%180-90;
const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-50,50,35,-35,.1,400);camera.up.set(0,0,1);
const pan=new THREE.Vector3(),focus=new THREE.Vector3(),sun=new THREE.DirectionalLight('#fff0ce',3),hemi=new THREE.HemisphereLight('#c9dce4','#7d8866',2);
const probe=new THREE.Raycaster(),UP=new THREE.Vector3(0,0,1),carPoint=new THREE.Vector3();
sun.position.set(-24,-35,48);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-45,right:45,bottom:-38,top:40,near:1,far:150});sun.shadow.normalBias=.025;sun.shadow.bias=-.0001;scene.add(sun,sun.target,hemi);
const THEMES={dawn:['#eadfd0','#ffc79d',1.9,1.6,.96],day:['#e8e9df','#fff0ce',3,2,1.02],sunset:['#e7d1ba','#ffbb77',2.2,1.55,.94],night:['#172c35','#a9c7df',.45,.48,.94]};
function schedule(){if(!raf&&!disposed&&ready&&!document.hidden)raf=requestAnimationFrame(frame);}
function controls(){document.querySelector('#play').textContent=running?'Ⅱ':'▷';document.querySelector('#play').setAttribute('aria-label',running?'暫停行駛':'開始行駛');document.querySelector('#play').setAttribute('aria-pressed',String(running));document.querySelector('#in').disabled=zoom>=1.8;document.querySelector('#out').disabled=zoom<=.7;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));}
function theme(next){if(!THEMES[next])return;period=next;const [bg,color,power,ambient,exposure]=THEMES[next];document.body.dataset.period=next;document.body.style.backgroundColor=bg;scene.background=new THREE.Color(bg);sun.color.set(color);sun.intensity=power;sun.position.set(next==='dawn'?25:-25,-30,next==='day'?48:20);hemi.intensity=ambient;hemi.color.set(next==='night'?'#7694b0':'#c9dce4');hemi.groundColor.set(next==='night'?'#243a36':'#7d8866');scene.environmentIntensity=next==='night'?.18:.65;renderer.toneMappingExposure=exposure;document.querySelectorAll('button[data-period]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.period===next)));schedule();}
function drawTrain(consist,follow,path,distance){
 follow(path,distance);consist.updateParts?.();consist.lighting.update(period==='dawn'?'sunrise':period,1);
 consist.root.visible=trainShown&&Math.abs(distance)<38+consist.length/2+.8;consist.root.updateMatrixWorld(true);
 consist.root.traverse(o=>{if(o.isSprite||o.isSpotLight){const p=new THREE.Vector3();o.getWorldPosition(p);o.visible=Math.abs(p.x)<35;}});
}
function draw(){if(!train||disposed)return;const distance=distanceAt(time),opposingDistance=distanceAt(time-3);
 drawTrain(train,follower,place.path,distance);if(opposing)drawTrain(opposing,opposingFollower,place.opposingPath,opposingDistance);
 place.update(time,period,{id:model,distance,opposingDistance,length:train.length,speed,cars:kind==='duoliang'&&train.root.visible?train.cars.map(c=>c.car.getWorldPosition(carPoint).toArray()):undefined});
 const rect=canvas.getBoundingClientRect(),aspect=rect.width/Math.max(1,rect.height);let heading=0;
 if(view==='train'){const p=place.path.sample(THREE.MathUtils.clamp(distance,-19,19));focus.set(p.x,p.y,p.z+1.0);heading=p.heading;}else focus.set(...place.focus);focus.add(pan);
 const orbit=yaw+heading;span=(view==='train'?Math.max(8,train.length*.7/aspect):Math.max(28,42/aspect))/zoom;
 Object.assign(camera,{left:-span*aspect,right:span*aspect,top:span,bottom:-span});camera.position.set(focus.x+100*Math.cos(elevation)*Math.cos(orbit),focus.y+100*Math.cos(elevation)*Math.sin(orbit),focus.z+100*Math.sin(elevation));camera.lookAt(focus);camera.updateProjectionMatrix();camera.updateMatrixWorld();scene.updateMatrixWorld(true);renderer.render(scene,camera);draws++;canvas.dataset.ready='true';document.querySelector('#status').textContent=kind==='crossing'?place.state.phase:'海風裡，等一班列車';}
function frame(t){raf=0;if(document.hidden||disposed)return;if(last&&t-last<32){schedule();return;}const dt=last?Math.min(.08,(t-last)/1000):0;last=t;if(running&&!changing)time+=dt;draw();if(running)schedule();}
function resize(){if(!renderer||disposed)return;const r=canvas.getBoundingClientRect();renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);schedule();}
function reset(){pan.set(0,0,0);zoom=1;yaw=-1.12;elevation=.61;controls();schedule();}
function setView(v){view=v;pan.set(0,0,0);controls();schedule();}
function setZoom(z,{focusTrain=true}={}){if(focusTrain&&view==='world'&&z>zoom){view='train';pan.set(0,0,0);z=1;}zoom=Math.max(.7,Math.min(1.8,z));controls();schedule();}
async function choose(id){if(!['blue','dr1000','emu3000'].includes(id))return;const token=++serial;controller?.abort();controller=new AbortController();changing=true;loading.hidden=false;loading.textContent='正在換上這班列車…';let asset,consist,other;
 try{asset=await loadGarageModel(id,controller.signal);consist=await createConsist(id,asset,controller.signal);if(place.opposingPath)other=await createConsist(id,asset,controller.signal);if(disposed||token!==serial){consist.dispose();other?.dispose();asset.dispose();return;}if(train){scene.remove(train.root);train.dispose();if(opposing){scene.remove(opposing.root);opposing.dispose();}primary.dispose();}train=consist;opposing=other;primary=asset;model=id;select.value=id;
 const clips=[new THREE.Plane(new THREE.Vector3(1,0,0),35),new THREE.Plane(new THREE.Vector3(-1,0,0),35)];
 for(const t of [train,opposing].filter(Boolean))for(const c of t.cars)for(const m of c.body.material){m.clippingPlanes=clips;m.clipShadows=true;m.needsUpdate=true;}
 for(const t of [train,opposing].filter(Boolean))for(const o of t.root.children)if(o.isMesh){o.material.clippingPlanes=clips;o.material.clipShadows=true;o.material.needsUpdate=true;}
 // 集電弓掛在車身底下，也要跟車身一起被場景兩端裁掉；弓頭高度由場景的接觸線決定（無線＝降弓）。
 for(const t of [train,opposing].filter(Boolean))for(const c of t.cars)c.body.traverse(o=>{if(o.isMesh&&o!==c.body){o.material.clippingPlanes=clips;o.material.clipShadows=true;o.material.needsUpdate=true;}});
 for(const t of [train,opposing].filter(Boolean))t.setContactWire?.(place.contactWireZ??null);
 scene.add(train.root);follower=createTerrainFollower(train);if(opposing){scene.add(opposing.root);opposingFollower=createTerrainFollower(opposing);}ready=true;changing=false;loading.hidden=true;draw();schedule();}
 catch(e){consist?.dispose();other?.dispose();asset?.dispose();if(token!==serial||disposed)return;changing=false;loading.textContent='小車暫時無法載入，請再選一次。';select.value=model;if(train)loading.hidden=true;else{const retry=document.createElement('button');retry.textContent='重新載入';retry.onclick=()=>choose(id);loading.append(retry);}console.error(e);}
}
select.onchange=()=>choose(select.value);
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>setView(b.dataset.view);
for(const b of document.querySelectorAll('button[data-period]'))b.onclick=()=>theme(b.dataset.period);
document.querySelector('#play').onclick=()=>{running=!running;last=0;controls();schedule();};document.querySelector('#reset').onclick=reset;
document.querySelector('#in').onclick=()=>setZoom(zoom*1.2);document.querySelector('#out').onclick=()=>setZoom(zoom/1.2);
document.querySelector('#feature').onclick=()=>{time=kind==='crossing'?(30-train.length/2-3.5-6.2*speed)/speed:30/speed;view='world';reset();running=kind==='crossing'&&!reduced.matches;controls();draw();schedule();};
function panBy(dx,dy){const heading=view==='train'?place.path.sample(distanceAt(time)).heading:0,a=yaw+heading,u=2*span/Math.max(1,canvas.clientHeight);pan.x=THREE.MathUtils.clamp(pan.x+Math.sin(a)*dx*u-Math.cos(a)*dy*u/Math.sin(elevation),-40,40);pan.y=THREE.MathUtils.clamp(pan.y-Math.cos(a)*dx*u-Math.sin(a)*dy*u/Math.sin(elevation),-40,40);schedule();}
const pointers=new Map();let gesture;
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,pan:e.button>0||e.shiftKey});gesture=null;};
canvas.onpointermove=e=>{const old=pointers.get(e.pointerId);if(!old)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,pan:old.pan});if(pointers.size===1){if(old.pan)panBy(e.clientX-old.x,e.clientY-old.y);else{yaw+=(e.clientX-old.x)*.007;elevation=THREE.MathUtils.clamp(elevation+(old.y-e.clientY)*.005,.23,1.2);schedule();}}else{const [a,b]=[...pointers.values()],gap=Math.hypot(a.x-b.x,a.y-b.y),mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(gesture){setZoom(gesture.zoom*gap/gesture.gap);panBy(mid.x-gesture.mid.x,mid.y-gesture.mid.y);gesture.mid=mid;}else gesture={gap:Math.max(1,gap),zoom,mid};}};
canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=e=>{pointers.delete(e.pointerId);gesture=null;};canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*Math.exp(-Math.max(-150,Math.min(150,e.deltaY))*.002),{focusTrain:false});},{passive:false});
canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','0',' '].includes(e.key))return;e.preventDefault();if(e.key===' ')document.querySelector('#play').click();else if(e.key==='0')reset();else if(e.key==='+')setZoom(zoom*1.2);else if(e.key==='-')setZoom(zoom/1.2);else if(e.shiftKey)panBy(e.key==='ArrowLeft'?40:e.key==='ArrowRight'?-40:0,e.key==='ArrowUp'?40:e.key==='ArrowDown'?-40:0);else{yaw+=(e.key==='ArrowRight'?.15:e.key==='ArrowLeft'?-.15:0);elevation=THREE.MathUtils.clamp(elevation+(e.key==='ArrowUp'?.1:e.key==='ArrowDown'?-.1:0),.23,1.2);schedule();}};
const observer=new ResizeObserver(resize);observer.observe(canvas);document.addEventListener('visibilitychange',()=>{last=0;if(document.hidden){cancelAnimationFrame(raf);raf=0;}else schedule();});reduced.addEventListener('change',()=>{if(reduced.matches){running=false;controls();schedule();}});
function dispose(){if(disposed)return;disposed=true;ready=false;serial++;controller?.abort();cancelAnimationFrame(raf);observer.disconnect();train?.dispose();opposing?.dispose();primary?.dispose();place?.dispose();visitorKits?.forEach(k=>k.dispose());env?.dispose();sun.shadow.map?.dispose();renderer?.dispose();}
window.addEventListener('pagehide',dispose);window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.localClippingEnabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();dispose();loading.hidden=false;loading.textContent='畫面暫時中斷，請重新載入。';const b=document.createElement('button');b.textContent='重新載入';b.onclick=()=>location.reload();loading.append(b);});
 const studio=new THREE.Scene();studio.background=new THREE.Color('#99aeb4');const pmrem=new THREE.PMREMGenerator(renderer);env=pmrem.fromScene(studio,.1);scene.environment=env.texture;pmrem.dispose();
 const {createScene}=await import(kind==='duoliang'?'../../rail-3d/garage-scenes/duoliang.js?revision=windows-0929':'../../rail-3d/garage-scenes/crossing.js?revision=drawcalls-0929');if(kind==='duoliang')visitorKits=await Promise.all(['garage-people-v1/people','garage-camera-v1/camera'].map(n=>loadGarageParts(new URL(`../../rail-3d/assets/${n}.json`,import.meta.url))));place=createScene(visitorKits);scene.add(place.group);theme(period);controls();resize();await choose(model);
 window.newScenePreview={get state(){return{ready,changing,kind,model,period,running,view,time,distance:distanceAt(time),speed,pathLength:place.path.length,trainLength:train?.length,opposing:opposing?{distance:distanceAt(time-3),visible:opposing.root.visible,poses:opposing.cars.map(c=>({position:c.car.position.toArray(),heading:c.heading,length:c.length,offset:c.offset})),lighting:opposing.lighting.state}:null,inScene:train?.root.visible,scene:place.state,lighting:train?.lighting.state,draws,yaw,camera:camera.position.toArray(),triangles:renderer.info.render.triangles,calls:renderer.info.render.calls,memory:{...renderer.info.memory},poses:train?.cars.map(c=>({id:c.id,position:c.car.position.toArray(),heading:c.heading,pitch:c.pitch,length:c.length,offset:c.offset}))};},setTime(t){time=t;draw();},trafficAt(t){place.update(t,period,{id:model,distance:distanceAt(t),opposingDistance:distanceAt(t-3),length:train.length,speed});return place.state;},samplePath(s,reverse=false){return (reverse?place.opposingPath:place.path).sample(s);},setPeriod:theme,choose,setView,render:draw,dispose,project(p){const q=new THREE.Vector3(...p).project(camera);return{x:(q.x+1)*canvas.width/2,y:(1-q.y)*canvas.height/2};},pantographs(){return [train,opposing].filter(Boolean).flatMap((t,k)=>(t.pantographState?.()??[]).map(h=>({...h,train:k?'opposing':'main',visible:t.root.visible})));},probeUp(p){probe.camera=camera;probe.set(new THREE.Vector3(...p),UP);const hit=probe.intersectObject(place.group,true)[0];return hit?hit.point.z:null;},inspect(){return place.inspect?.()??[];},probeDown(p){probe.camera=camera;probe.set(new THREE.Vector3(...p),new THREE.Vector3(0,0,-1));const hit=probe.intersectObject(place.group,true)[0];return hit?hit.point.z:null;},trainBox(){const b=new THREE.Box3(),h=new THREE.Box3();for(const c of train.cars){c.body.updateWorldMatrix(true,false);h.copy(c.body.geometry.boundingBox).applyMatrix4(c.body.matrixWorld);b.union(h);}return{min:b.min.toArray(),max:b.max.toArray()};},trainVisible(v){trainShown=v;draw();},sceneVisible(v){place.group.visible=v;draw();},sceneLightsVisible(v){place.group.traverse(o=>{if(o.isLight)o.visible=v;});draw();}};
}catch(e){console.error(e);loading.hidden=false;loading.textContent='風景暫時無法載入，請重新整理。';}
