import {chromium,webkit} from 'playwright';
import {mkdirSync,writeFileSync} from 'node:fs';
const out='output/garage-wave1-refined';mkdirSync(out,{recursive:true});const results=[];
function check(name,pass,data){results.push({name,pass:!!pass,data});console.log(pass?'PASS':'FAIL',name,JSON.stringify(data??''));}
for(const [engine,type]of Object.entries(process.env.ENGINE==='webkit'?{webkit}:process.env.QUICK||process.env.ENGINE==='chromium'?{chromium}:{chromium,webkit})){
 const browser=await type.launch();try{for(const kind of process.env.SCENE?[process.env.SCENE]:['duoliang','crossing']){
 const p=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto(`http://127.0.0.1:5291/prototypes/garage-${kind}/`);await p.waitForFunction(()=>window.newScenePreview?.state.ready,null,{timeout:60000});
 await p.evaluate(()=>{newScenePreview.setPeriod('day');newScenePreview.setView('world');newScenePreview.setTime(30/2.6);});await p.screenshot({path:`${out}/${engine}-${kind}-day.png`});
 if(process.env.QUICK){check(`${engine} ${kind} 載入`,true,await p.evaluate(()=>({scene:newScenePreview.state.scene,calls:newScenePreview.state.calls,triangles:newScenePreview.state.triangles})));await p.close();continue;}
 for(const id of ['blue','dr1000','emu3000']){await p.selectOption('#train',id);await p.waitForFunction(id=>newScenePreview.state.model===id&&!newScenePreview.state.changing,id);const sample=await p.evaluate(()=>{const a=newScenePreview;return [-25,-12,0,12,25].map(d=>{a.setTime((30+d)/2.6);const s=a.state;return {...s,track:s.poses.map(c=>a.samplePath(d+c.offset))};});});
 check(`${engine} ${kind} ${id} 車廂貼合軌道`,sample.every(s=>s.poses.every((c,i)=>Math.hypot(c.position[0]-s.track[i].x,c.position[1]-s.track[i].y)<.08&&Math.abs(c.position[2]-s.track[i].z)<.02)),sample.map(s=>s.poses.map(c=>c.heading)));
 if(kind==='crossing')check(`${engine} ${id} 雙股反向通過`,sample.every(s=>s.opposing.poses.length===3&&s.poses.every(c=>Math.abs(c.position[1]-1.65)<1e-7)&&s.opposing.poses.every(c=>Math.abs(c.position[1]+1.65)<1e-7&&Math.abs(Math.abs(c.heading)-Math.PI)<1e-7))&&sample[4].opposing.poses[1].position[0]<sample[0].opposing.poses[1].position[0]);
 }
 if(kind==='duoliang'){const s=await p.evaluate(()=>{const a=newScenePreview;return {left:a.samplePath(-25),right:a.samplePath(25),stairs:a.state.scene.stairs};});check(`${engine} 多良彎軌與階梯連接`,s.left.heading<-.2&&s.right.heading>.2&&s.stairs[0].steps===15&&Math.abs(s.stairs[0].top[2]-6.9)<1e-8,s);}
 else {const stats=await p.evaluate(()=>{const a=newScenePreview;let occupied=0,violations=0,both=0,clear=0;for(let t=0;t<180/2.6;t+=.22){const s=a.trafficAt(t);if(s.occupied){occupied++;if(s.closed<.999999)violations++;if(s.vehicles.some(v=>Math.abs(v.y)-v.length/2<4.6))violations++;}if(s.trains.every(t=>t.occupied))both++;if(!s.alarm&&s.closed===0)clear++;}return {occupied,violations,both,clear};});check(`${engine} 雙線都清空才放行`,stats.occupied>0&&stats.both>0&&stats.clear>0&&stats.violations===0,stats);}
 for(const period of ['dawn','day','sunset','night']){await p.click(`[data-period="${period}"]`);await p.evaluate(()=>{newScenePreview.setView('world');newScenePreview.setTime(30/2.6+1.5);});const s=await p.evaluate(()=>newScenePreview.state);check(`${engine} ${kind} ${period}`,s.scene.lights===(period==='night'?1:period==='day'?0:.35));await p.screenshot({path:`${out}/${engine}-${kind}-${period}.png`});}
 await p.click('[data-view="train"]');await p.screenshot({path:`${out}/${engine}-${kind}-follow.png`});
 await p.click('[data-period="day"]');await p.click('[data-view="world"]');for(let i=0;i<12;i++)await p.locator('#scene').press('ArrowRight');await p.evaluate(()=>newScenePreview.render());await p.screenshot({path:`${out}/${engine}-${kind}-back.png`});
 for(const width of [360,375,414,768]){const m=await browser.newPage({viewport:{width,height:920},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await m.goto(`http://127.0.0.1:5291/prototypes/garage-${kind}/`);await m.waitForFunction(()=>window.newScenePreview?.state.ready);await m.tap('[data-period="night"]');await m.tap('#in');const controls=m.locator('button,select,nav a'),unreachable=[];for(let i=0;i<await controls.count();i++){const el=controls.nth(i);await el.scrollIntoViewIfNeeded();const hit=await el.evaluate(e=>{const r=e.getBoundingClientRect(),at=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{hit:at===e||e.contains(at),height:r.height};});if(!hit.hit||hit.height<44)unreachable.push(i);}
 const layout=await m.evaluate(()=>{const rs=[...document.querySelectorAll('button,select,nav a')].map(e=>e.getBoundingClientRect()),overlaps=[];for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++){const a=rs[i],b=rs[j];if(Math.min(a.right,b.right)-Math.max(a.left,b.left)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>1)overlaps.push([i,j]);}return{overflow:document.documentElement.scrollWidth>innerWidth,overlaps,period:newScenePreview.state.period};});check(`${engine} ${kind} 手機 ${width}`,!layout.overflow&&!layout.overlaps.length&&!unreachable.length&&layout.period==='night',{...layout,unreachable});if(width===375){await m.locator('#scene').scrollIntoViewIfNeeded();await m.screenshot({path:`${out}/${engine}-${kind}-mobile.png`});}await m.close();}
 check(`${engine} ${kind} 無程式錯誤`,!errors.length,errors);await p.close();
 }}finally{await browser.close();}
}
writeFileSync(`${out}/verification.json`,JSON.stringify(results,null,2));if(results.some(r=>!r.pass))process.exitCode=1;
