import fs from 'node:fs';import {chromium,webkit} from 'playwright';
const base=process.env.BASE_URL||'http://127.0.0.1:5233/',rows=[];
for(const [engine,type]of Object.entries({chromium,webkit})){const browser=await type.launch();for(const width of [360,375,414,768]){const page=await browser.newPage({viewport:{width,height:900},isMobile:true,hasTouch:true,locale:'zh-TW'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));
try{await page.goto(base+'?scene=3d&map=landscape&g=all&at=25.0477,121.5171&z=17&t=08:00');await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&window.railIslandIntegration?.renderer?.stats.undergroundModels>0,null,{timeout:90000});await page.evaluate(()=>state.playing=false);
for(const fullscreen of [true]){await page.evaluate(fullscreen=>{if(document.body.classList.contains('fs')!==fullscreen)document.getElementById('fsFab').click();},fullscreen);for(const mode of ['flat','terrain']){await page.locator(await page.locator('#toolsFab').isVisible()?'#toolsFab':'#tabMore').tap();const target=page.locator('[data-rail3d="ground"] [data-value="'+mode+'"]');await target.scrollIntoViewIfNeeded();const reachable=await target.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));});await target.tap();await page.locator('#moreClose').tap();await page.waitForFunction(mode=>window.railIslandIntegration?.renderer?.stats.groundMode===mode&&window.railIslandIntegration?.renderer?.stats.undergroundModels>0,mode,{timeout:30000});
const detail=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,models:railIslandIntegration.renderer.stats.undergroundModels,fs:document.body.classList.contains('fs'),errors:railIslandIntegration.renderer.stats.errors,heights:railIslandIntegration.renderer.stats.poseSamples.filter(p=>p.underground).map(p=>p.displayHeightM)}));rows.push({engine,width,fullscreen,mode,pass:reachable&&!detail.overflow&&!detail.errors.length&&detail.fs===fullscreen,detail});console.log(JSON.stringify(rows.at(-1)));}}
rows.push({engine,width,test:'無頁面錯誤',pass:!errors.length,errors});
}catch(e){rows.push({engine,width,pass:false,error:String(e)});console.log(e);}finally{await page.close();}}await browser.close();}
fs.mkdirSync('output/rail-levels',{recursive:true});fs.writeFileSync('output/rail-levels/mobile.json',JSON.stringify(rows,null,2));if(rows.some(r=>!r.pass))process.exitCode=1;
