import {chromium,webkit} from 'playwright';
import {panChecks} from './lib/garage_pan_checks.mjs';
import {mkdirSync,writeFileSync} from 'node:fs';
import {createRoutes,createJourney} from '../rail-3d/garage-scenes/alishan-route.js';
const OUT='output/alishan',URL='http://127.0.0.1:5252/prototypes/garage-alishan/';mkdirSync(OUT,{recursive:true});
const results=[];function check(name,pass,detail){results.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail??''));}
const state=p=>p.evaluate(()=>alishanPreview.state),settle=p=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const routes=createRoutes(),journey=createJourney(routes,13.628863594123153);let maxJump=0,maxSlope=0;
for(const stage of journey.stages){const t=stage.start+stage.duration,a=journey.at(t-1e-6),b=journey.at(t+1e-6);for(const offset of [-6.8,-4,0,4,6.8]){const p=routes[a.route].sample(a.s+offset),q=routes[b.route].sample(b.s+offset);maxJump=Math.max(maxJump,Math.hypot(p.x-q.x,p.y-q.y,p.z-q.z));}}
check('全部六個階段銜接含完整編組端點無瞬移',maxJump<1e-6,{maxJump});
for(const r of routes)for(let s=.2;s<r.length-.2;s+=.2){const a=r.sample(s-.1),b=r.sample(s+.1);maxSlope=Math.max(maxSlope,Math.abs((a.z-b.z)/Math.hypot(a.x-b.x,a.y-b.y)));}check('路徑有實際坡度與 11 單位高差',maxSlope>.1&&routes[2].sample(routes[2].length).z-routes[0].sample(0).z===11,{maxSlope});
for(const [engine,type]of Object.entries({chromium,webkit})){
 const b=await type.launch({headless:true});
 try{
  const p=await b.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1,isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto(URL);await p.waitForFunction(()=>window.alishanPreview?.state.ready,null,{timeout:90000});await p.tap('#play');await settle(p);
  check(engine+' 編組＝DL38 ＋ 兩節林鐵客車',JSON.stringify([...(await state(p)).poses.map(c=>c.id)].sort())===JSON.stringify(['alicoach','alicoach','dl38']),(await state(p)).poses.map(c=>c.id));
  // 阿里山林鐵的機關車固定連結在下山端、以推進方式運轉上山（交通部觀光署與農業部都記載之字形「時而前拖、時而後推」）。
  // 判準取兩個端點：從山腳起步那段必為推進，回到山腳那段必為牽引。中間的交替是折返本身逼出來的。
  const locoEnd=await p.evaluate(()=>{const api=alishanPreview,st=api.state.stages,out=[];
   for(const i of [0,st.length-1]){const g=st[i];api.setTime(g.start+g.travel/2);const ps=api.state.poses;
    const loco=ps.find(c=>c.id==='dl38'),other=ps.find(c=>c.id!=='dl38');
    const along=(loco.x-other.x)*Math.cos(loco.heading)+(loco.y-other.y)*Math.sin(loco.heading);
    out.push({stage:g.label,sign:g.sign,leading:along*g.sign>0});}
   return out;});
  check(engine+' 機關車固定在下山端：上山推進、下山牽引',locoEnd[0].leading===false&&locoEnd[1].leading===true,locoEnd);
  const alignment=await p.evaluate(()=>{const api=alishanPreview,s=api.state,rows=[];for(const stage of s.stages)for(const f of [.25,.5,.75]){api.setTime(stage.start+stage.travel*f);const a=api.state;let clearanceMin=Infinity,clearanceMax=-Infinity,pitch=0;for(const c of a.poses){pitch=Math.max(pitch,Math.abs(c.pitch));for(const ds of [-.3,.3]){const p=api.sample(a.pose.route,a.pose.s+c.offset+c.length*ds),z=api.surface([p.x,p.y]),clearance=p.z-z;clearanceMin=Math.min(clearanceMin,clearance);clearanceMax=Math.max(clearanceMax,clearance);}}rows.push({stage:a.pose.stage,clearanceMin,clearanceMax,pitch});}return rows;});
  check(engine+' 上下山六階段車輪路徑高於真實地表網格',alignment.every(r=>r.clearanceMin>0&&r.clearanceMax<.5)&&alignment.some(r=>r.pitch>.1),alignment);
  const continuity=await p.evaluate(()=>{const api=alishanPreview,stages=api.state.stages;let jump=0,angle=0,dwell=0;for(const s of stages){const t=s.start+s.duration;api.setTime(t-.00001);const a=api.state.poses;api.setTime(t+.00001);const b=api.state.poses;for(let i=0;i<a.length;i++){jump=Math.max(jump,Math.hypot(a[i].x-b[i].x,a[i].y-b[i].y,a[i].z-b[i].z));angle=Math.max(angle,Math.abs(a[i].heading-b[i].heading),Math.abs(a[i].pitch-b[i].pitch));}api.setTime(s.start+s.travel+.2);const c=JSON.stringify(api.state.poses);api.setTime(s.start+s.travel+2.8);if(c===JSON.stringify(api.state.poses)&&!api.state.pose.moving)dwell++;}return{jump,angle,dwell};});check(engine+' 折返與上下端停車不跳位／不翻頭／停足三秒',continuity.jump<1e-5&&continuity.angle<1e-5&&continuity.dwell===6,continuity);
  await p.evaluate(()=>alishanPreview.setTime(4));
  const pixel=await p.evaluate(async()=>{const api=alishanPreview,c=document.querySelector('#scene'),out=document.createElement('canvas');out.width=c.width;out.height=c.height;const ctx=out.getContext('2d'),read=async()=>{const im=new Image();im.src=c.toDataURL();await im.decode();ctx.drawImage(im,0,0);return ctx.getImageData(0,0,c.width,c.height).data;};api.trainVisible(false);const empty=await read();api.trainVisible(true);const full=await read();return api.state.bounds.map(b=>{let changed=0;for(let y=Math.max(0,Math.floor(b.top));y<Math.min(c.height,b.bottom);y++)for(let x=Math.max(0,Math.floor(b.left));x<Math.min(c.width,b.right);x++){const i=(y*c.width+x)*4;if(Math.abs(full[i]-empty[i])+Math.abs(full[i+1]-empty[i+1])+Math.abs(full[i+2]-empty[i+2])>25)changed++;}return changed;});});check(engine+' 三節車體的實際像素',pixel.every(n=>n>30),pixel);
  for(const period of ['day','sunset','night']){await p.tap('button[data-period="'+period+'"]');await settle(p);await p.screenshot({path:`${OUT}/${engine}-${period}.png`});check(engine+' '+period+' 光影可切換',(await state(p)).period===period);}
  await p.tap('button[data-period="day"]');await p.tap('[data-view="train"]');await settle(p);check(engine+' 跟車構圖三節完整',await p.evaluate(()=>{const c=document.querySelector('#scene');return alishanPreview.state.bounds.every(b=>b.left>0&&b.right<c.width&&b.top>0&&b.bottom<c.height);}));await p.screenshot({path:`${OUT}/${engine}-follow.png`});
  await p.tap('#switchback');await p.waitForFunction(()=>alishanPreview.state.pose.stage===0&&!alishanPreview.state.pose.moving,null,{timeout:45000});const stopped=await state(p);await p.waitForFunction(()=>alishanPreview.state.pose.stage===1&&alishanPreview.state.pose.moving,null,{timeout:30000});await p.tap('#play');await settle(p);const reversed=await state(p);check(engine+' 真實動畫停車後換線倒推',stopped.pose.route===0&&reversed.pose.route===1&&reversed.pose.sign===-1,{stopped:stopped.pose,reversed:reversed.pose});
  await p.evaluate(()=>{const s=alishanPreview.state.stages[1];alishanPreview.setTime(s.start+s.travel*.5);});await p.screenshot({path:`${OUT}/${engine}-climb.png`});
  await panChecks({b,engine,URL,api:'alishanPreview',check,settle});   // 鏡頭平移（四頁共用的判準，在自己開的桌面頁與觸控頁上量）
  await p.tap('[data-view="world"]');await p.evaluate(()=>alishanPreview.setTime(4));
  for(const width of [360,375,390,414,520,768,1280]){await p.setViewportSize({width,height:900});await settle(p);await p.tap('#in');await p.tap('#out');await p.tap('#reset');await settle(p);const ui=await p.evaluate(()=>{const els=[...document.querySelectorAll('button,a')].filter(e=>e.getClientRects().length),bad=[],overlap=[];for(const e of els){const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);if(!e.contains(hit)||r.width<43||r.height<43)bad.push(e.textContent);}for(let i=0;i<els.length;i++)for(let j=i+1;j<els.length;j++){const a=els[i].getBoundingClientRect(),b=els[j].getBoundingClientRect();if(Math.min(a.right,b.right)-Math.max(a.left,b.left)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>1)overlap.push([els[i].textContent,els[j].textContent]);}return{bad,overlap,overflow:document.documentElement.scrollWidth>innerWidth};});check(engine+' '+width+' 真觸控與可及性',!ui.bad.length&&!ui.overlap.length&&!ui.overflow,ui);}
  const mem=(await state(p)).memory;for(let i=0;i<3;i++){await p.tap('[data-view="train"]');await p.tap('button[data-period="night"]');await p.tap('[data-view="world"]');await p.tap('button[data-period="day"]');}await settle(p);check(engine+' 切換不累積資源',JSON.stringify(mem)===JSON.stringify((await state(p)).memory));const draws=(await state(p)).draws;await p.waitForTimeout(250);check(engine+' 暫停不重繪',(await state(p)).draws===draws);check(engine+' 無 JS／WebGL 錯誤',errors.length===0,errors);await p.close();
  const mobile=await b.newPage({viewport:{width:375,height:900},reducedMotion:'reduce',isMobile:true,hasTouch:true});await mobile.goto(URL);await mobile.waitForFunction(()=>window.alishanPreview?.state.ready,null,{timeout:90000});check(engine+' 手機預設跟車且減少動態停止',!(await state(mobile)).running&&(await state(mobile)).view==='train');await mobile.evaluate(()=>alishanPreview.setTime(4));await mobile.screenshot({path:`${OUT}/${engine}-mobile.png`,fullPage:true});await mobile.close();
 }catch(e){check(engine+' 驗證流程',false,e.stack);}finally{await b.close();}
}
writeFileSync(OUT+'/results.json',JSON.stringify(results,null,2));if(results.some(r=>!r.pass))process.exitCode=1;
