// 直接檢查出貨派車表與完整來源節點走法，再用產品行車剖面驗收改動站段。
import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{restorePhysicalRoutes}from'./lib/restore_physical_routes.mjs';import{computeProfiles,readPassObs}from'./build_run_profiles.mjs';import{createPhysicalMotion,physicalTrainKey}from'../rail-3d/physical/motion.js';import{distanceM}from'../rail-3d/integration/train-path.js';
const read=f=>JSON.parse(fs.readFileSync(f)),net=read(process.env.NETWORK||'rail-3d/physical/network.json'),dispatch=read(process.env.DISPATCH||'rail-3d/physical/dispatch.json'),proof=read('scripts/fixtures/remaining-routes-0913.json');assert.equal(crypto.createHash('sha256').update(JSON.stringify(net.ways)).digest('hex'),proof.waysSha256,'本批不得橫移或新造來源股道');for(const[k,p]of Object.entries(proof.afterPlans))assert.deepEqual(dispatch.plans[k],p,'已驗收的進路或模板保護退回 '+k);
const{g,paths}=restorePhysicalRoutes(net);for(const[id,p]of Object.entries(proof.newPaths)){assert.deepEqual(net.paths[id],p,'已驗收路徑被改寫 '+id);assert.equal(p.fromGroup,p.system+':'+(g.trackGroups.get(p.from)||p.from));assert.equal(p.toGroup,p.system+':'+(g.trackGroups.get(p.to)||p.to));}
const baseline={...dispatch,plans:{...dispatch.plans}};for(const[k,p]of Object.entries(proof.beforePlans)){if(p)baseline.plans[k]=p;else delete baseline.plans[k];}const sourceStops=new Set(Object.values(baseline.plans).flatMap(p=>p.pathIds.flatMap(id=>[paths[id].from,paths[id].to])));for(const c of proof.changes)if(c.toNode)assert(sourceStops.has(c.toNode),'不得拿未被原派車表使用的股道冒充月台');
const schedule=read('data/tra_schedule_dense.json');computeProfiles({indexPath:'index.html',schedule,track:read('data/tra.json'),passObs:readPassObs('data/tra_pass_obs.json')});const profiles=read('rail-3d/physical/display-profiles.json'),levels=read('rail-3d/physical/level-profiles.json');for(const[id,p]of Object.entries(profiles.entries))p.level=levels.entries[id];const motion=createPhysicalMotion(net,profiles,dispatch),oldMotion=createPhysicalMotion(net,profiles,baseline),changed=new Set(proof.changes.map(c=>c.key));let samples=0,boundaries=0,forward=0,backward=0,maxJump=0,protectedCount=0;const seen=new Set();
for(const tr of schedule.trains){const key=physicalTrainKey(tr),r=motion.record(tr),old=oldMotion.record(tr);if(!changed.has(key)){if(old){assert(r,'未改車班失去綁定 '+key);assert.deepEqual(r.plan.pathIds,old.plan.pathIds,'未改車班因模板變更被動換軌 '+key);}if(proof.protectedTemplates.includes(key))protectedCount++;continue;}assert(r&&old,'改動車班必須能綁定 '+key);seen.add(key);assert(!r.plan.holds.some(h=>h.arrival||h.departure),'不得用額外 hold 掩蓋互穿');const ids=r.plan.pathIds;
for(let i=1;i<ids.length;i++){const a=paths[ids[i-1]],b=paths[ids[i]];assert.equal(a.to,b.from);if(old.plan.pathIds[i-1]===ids[i-1]&&old.plan.pathIds[i]===ids[i])continue;assert(g.canTurn(a.nodeIds.at(-2),a.to,b.nodeIds[1],g.edges.get(a.edgeIds.at(-1)),g.edges.get(b.edgeIds[0])),'道岔不得倒車 '+key);for(const t of[tr.stops[i].arrSec,tr.stops[i].depSec]){const p=motion.sample(tr,t-.001),q=motion.sample(tr,t+.001);if(!p||!q)continue;const jump=distanceM([p.lon,p.lat],[q.lon,q.lat]);maxJump=Math.max(maxJump,jump);assert(jump<1,'進出站跳躍 '+key);boundaries++;if(q.lat>p.lat)forward++;if(q.lat<p.lat)backward++;}}
for(const c of proof.changes.filter(c=>c.key===key)){let prev=null;for(let t=Math.ceil(c.from);t<=c.to;t++){const p=motion.sample(tr,t);if(!p)continue;assert(p.physical);for(const mode of['flat','terrain'])assert(Number.isFinite(p.route.elevation(p.chainageM,mode)));if(prev)assert(distanceM([p.lon,p.lat],[prev.lon,prev.lat])<70,'每秒位移異常 '+key);prev=p;samples++;}}
}
assert.equal(seen.size,changed.size,'改動名冊分母不得縮水');assert(forward>0&&backward>0);assert.equal(protectedCount,proof.protectedTemplates.length);console.log({trains:seen.size,changes:proof.changes.length,samples,boundaries,forward,backward,maxBoundaryJumpM:maxJump,protectedCount});
