import {chromium,webkit} from 'playwright';
import {mkdirSync,writeFileSync} from 'node:fs';
import {crossingState} from '../rail-3d/garage-scenes/crossing-cycle.js';
const OUT='output/garage-wave1';mkdirSync(OUT,{recursive:true});const results=[];
function check(name,pass,detail){results.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail??''));}
for(const length of [10,15,24]){let violations=0;const phases=new Set();for(let d=-72;d<72;d+=.1){const s=crossingState(d,length,144);phases.add(s.phase);if(s.occupied&&s.closed<1-1e-8)violations++;if(s.closed<1&&s.clear<0&&s.arrival>0)violations++;}check(`編組 ${length} 全列清空才升桿`,violations===0&&phases.size===5,{violations,phases:[...phases]});}
for(const [engine,type]of Object.entries({chromium,webkit})){
 const browser=await type.launch();try{for(const kind of ['duoliang','crossing']){
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(`http://127.0.0.1:5291/prototypes/garage-${kind}/`);await page.waitForFunction(()=>window.newScenePreview?.state.ready,null,{timeout:90000});if((await page.evaluate(()=>newScenePreview.state)).running)await page.click('#play');
 for(const id of ['blue','dr1000','emu3000']){await page.selectOption('#train',id);await page.waitForFunction(id=>newScenePreview.state.model===id&&!newScenePreview.state.changing,id);await page.evaluate(()=>{newScenePreview.setView('world');newScenePreview.setTime(30/2.6);});const state=await page.evaluate(()=>newScenePreview.state);check(`${engine} ${kind} ${id} 編組與場景`,state.poses.length===3&&state.scene.electrified===(id==='emu3000'),{length:state.trainLength,calls:state.calls,triangles:state.triangles});}
 for(const period of ['dawn','day','sunset','night']){await page.click(`[data-period="${period}"]`);await page.evaluate(()=>newScenePreview.render());const s=await page.evaluate(()=>newScenePreview.state);check(`${engine} ${kind} ${period} 場景照明`,s.period===period&&s.scene.lights===(period==='night'?1:period==='day'?0:.35),s.lighting);await page.screenshot({path:`${OUT}/${engine}-${kind}-${period}.png`});}
 await page.click('[data-period="day"]');await page.click('[data-view="train"]');
 const turn=await page.evaluate(()=>{const api=newScenePreview;api.setTime((30+24)/2.6);const a=api.state;api.setTime((30+35)/2.6);const b=api.state;return{a,b};});check(`${engine} ${kind} 單向穿越、鏡頭在出口停留`,turn.a.poses.every(c=>Math.abs(c.heading)<1e-8)&&turn.b.poses.every(c=>Math.abs(c.heading)<1e-8)&&turn.b.poses[1].position[0]>turn.a.poses[1].position[0]);
 const exit=await page.evaluate(()=>{const api=newScenePreview;api.setTime((30+89.9)/2.6);const a=api.state;api.setTime((30+90.1)/2.6);const b=api.state;return{a:a.inScene,b:b.inScene,ax:a.poses[1].position[0],bx:b.poses[1].position[0]};});check(`${engine} ${kind} 全列離景後才重新進場`,!exit.a&&!exit.b&&exit.ax>80&&exit.bx<-80,exit);
 await page.evaluate(()=>newScenePreview.setTime(30/2.6));await page.screenshot({path:`${OUT}/${engine}-${kind}-follow.png`});
 if(kind==='crossing'){const states=await page.evaluate(()=>{const api=newScenePreview,len=api.state.trainLength;return[-len/2-3.5-5*2.6,-len/2-3.5-3*2.6,0,len/2+3.5+1.5*2.6,len/2+3.5+4*2.6].map(d=>{api.setTime((d+30)/2.6);return api.state.scene;});});check(`${engine} 遮斷與車流`,states.every(s=>!s.occupied||s.closed===1)&&states[2].vehicles.every(v=>Math.abs(v.y)-v.length/2>3.1)&&states[0].closed===0&&states[4].closed===0,states);}
 for(const width of [360,375,414,768]){const mobile=await browser.newPage({viewport:{width,height:920},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await mobile.goto(`http://127.0.0.1:5291/prototypes/garage-${kind}/`);await mobile.waitForFunction(()=>window.newScenePreview?.state.ready);await mobile.tap('[data-period="night"]');await mobile.tap('#in');const layout=await mobile.evaluate(()=>{const controls=[...document.querySelectorAll('button,select,nav a')],visible=controls.map(e=>({e,r:e.getBoundingClientRect()})),overlaps=[];for(let i=0;i<visible.length;i++)for(let j=i+1;j<visible.length;j++){const a=visible[i].r,b=visible[j].r;if(Math.min(a.right,b.right)-Math.max(a.left,b.left)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>1)overlaps.push([visible[i].e.id,visible[j].e.id]);}return{overflow:document.documentElement.scrollWidth>innerWidth,overlaps,touch:visible.every(({r})=>r.height>=44),period:newScenePreview.state.period,running:newScenePreview.state.running};});check(`${engine} ${kind} 手機 ${width}`,!layout.overflow&&!layout.overlaps.length&&layout.touch&&layout.period==='night'&&!layout.running,layout);await mobile.close();}
 check(`${engine} ${kind} 無程式錯誤`,!errors.length,errors);await page.close();
 }}finally{await browser.close();}
}
writeFileSync(`${OUT}/verification.json`,JSON.stringify(results,null,2));if(results.some(r=>!r.pass))process.exitCode=1;
