import fs from 'node:fs';import {chromium,webkit} from 'playwright';
const base=process.env.BASE_URL||'http://127.0.0.1:5234/',rows=[];
for(const [engine,type]of Object.entries({chromium,webkit})){const browser=await type.launch(),page=await browser.newPage({viewport:{width:375,height:900},isMobile:true,hasTouch:true,locale:'zh-TW'});await page.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));
try{await page.goto(base+'?g=all&scene=3d&map=landscape&t=12:00');await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&railIslandIntegration.renderer,null,{timeout:90000});await page.evaluate(()=>{state.playing=false;railIslandIntegration.setModelMode('selected');});
for(const [system,direction]of [['thsr_sched',1],['thsr_sched',-1],['mrt',1],['mrt',-1]]){const target=await page.evaluate(({system,direction})=>{clearFollow();clearFreqFollow();const v=railIslandIntegration.capture().vehicles.find(v=>v.systemId===system&&v.direction===direction&&v.route?.physical&&(system!=='mrt'||v.routeId==='R'));if(!v)throw Error('沒有測例 '+system+':'+direction);railIslandIntegration.select(v.id);M.raw.jumpTo({zoom:18,pitch:50});return {id:v.id,system,direction};},{system,direction});
for(const mode of ['flat','terrain']){await page.evaluate(mode=>railIslandIntegration.setGroundMode(mode),mode);await page.waitForFunction(id=>{const r=railIslandIntegration.renderer;return r.stats.poseSamples.some(p=>p.id===id)&&r.stats.headLockErrorPx<1;},target.id,{timeout:45000});const detail=await page.evaluate(()=>{const r=railIslandIntegration.renderer;return {error:r.stats.headLockErrorPx,framing:r.stats.followFraming,errors:r.stats.errors,builds:r.stats.routeBuilds};});rows.push({engine,...target,mode,pass:detail.error<1&&!detail.errors.length,detail});console.log(engine,system,direction,mode,rows.at(-1).pass);}
}
// 相機約束與 MapLibre 地表投影跨層比對，取同一個實際 render 事件中的矩陣。
const cross=await page.evaluate(()=>new Promise(resolve=>{const samples=[];let frames=0;state.playing=true;const onRender=()=>{const r=railIslandIntegration.renderer,c=r.map.getCenter().toArray(),ground=r.map.queryTerrainElevation(c),a=r.projectCoordinate(c,ground??0),b=r.map.project(c);samples.push(Math.hypot(a.x-b.x,a.y-b.y));if(++frames===20){r.map.off('render',onRender);state.playing=false;resolve({frames,max:Math.max(...samples)});}};M.raw.on('render',onRender);}));rows.push({engine,test:'行進中底圖與3D地表投影同步',pass:cross.max<.5,detail:cross});
}catch(e){rows.push({engine,pass:false,error:String(e)});}finally{await browser.close();}}
fs.mkdirSync('output/head-lock',{recursive:true});fs.writeFileSync(process.env.RESULT_FILE||'output/head-lock/targets.json',JSON.stringify(rows,null,2));console.log({total:rows.length,failed:rows.filter(r=>!r.pass)});if(rows.some(r=>!r.pass))process.exitCode=1;
