import {chromium,webkit} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:5246',engine=process.env.ENGINE||'chromium',out=process.env.OUT||'output/view-guide';await mkdir(out,{recursive:true});
let page;const rows=[],errors=[],check=(name,pass,data)=>{rows.push({name,pass:!!pass,data});console.log(pass?'PASS':'FAIL',name,JSON.stringify(data??''));};
// 使用者 2026-09-23 裁示瀏覽器測試一律無視窗(有視窗會搶焦點、把畫面切走)。Chromium 帶 channel:'chromium' 走真 GPU 的無視窗模式;預設 headless shell 是 SwiftShader 軟體算繪。
const b=await {chromium,webkit}[engine].launch(engine==='chromium'?{channel:'chromium',headless:true}:{headless:true});
try{const c=await b.newContext({viewport:{width:1280,height:950},locale:'zh-TW',isMobile:true,hasTouch:true}),p=await c.newPage();page=p;p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));await p.route('**/api/**',r=>r.fulfill({status:503,body:'{}'}));
await p.goto(base+'/?scene=3d&g=all&train=117&t=12:00&z=18&appearance=light&verify=v0914c');await p.waitForFunction(()=>window.railIslandIntegration?.renderer?.stats.models>0,null,{timeout:60000});await p.waitForFunction(()=>railIslandIntegration.guide&&window.railViewControls);await p.evaluate(()=>{state.playing=false;setSimSec(43200);});await p.waitForTimeout(500);
await p.evaluate(()=>{const r=railIslandIntegration.renderer;r.map.jumpTo({pitch:55,bearing:37,zoom:18});window.viewFrames=[];r.map.on('render',()=>{const v=railIslandIntegration.frame?.vehicles.find(v=>v.followed),a=v&&r.projectedVehicles().find(p=>p.id===v.id),q=v&&r.map.project([v.longitude,v.latitude]);viewFrames.push({pitch:r.map.getPitch(),id:v?.id,lock:state.followLock,error:a&&q?Math.hypot(a.x-q.x,a.y-q.y):null,head:r.stats.headLockErrorPx});});state.playing=true;});
await p.evaluate(()=>Promise.race([railIslandIntegration.setPerspective('flat'),new Promise((_,reject)=>setTimeout(()=>reject(Error('視角過場逾時 '+JSON.stringify({active:railIslandIntegration.renderer.transitioning,view:railIslandIntegration.renderer.getView(),hidden:document.hidden,frames:viewFrames.length}))),12000))]));let f=await p.evaluate(()=>viewFrames);check('連續轉俯視、同車跟隨',f.filter(v=>v.pitch>1&&v.pitch<54).length>5&&f.every(v=>v.id===f[0].id&&v.lock),{frames:f.length,intermediate:f.filter(v=>v.pitch>1&&v.pitch<54).length});check('轉場車頭保持鎖定',f.every(v=>v.head==null||v.head<3),{max:Math.max(...f.map(v=>v.head||0))});
await p.evaluate(()=>Promise.race([railIslandIntegration.setPerspective('tilt'),new Promise((_,reject)=>setTimeout(()=>reject(Error('還原過場逾時')),12000))]));check('還原原角度',await p.evaluate(()=>Math.abs(M.getPitch()-55)<.01&&Math.abs(M.getBearing()-37)<.01));
await p.evaluate(()=>{state.playing=false;railIslandIntegration.setPerspective('flat');});await p.waitForTimeout(250);await p.evaluate(()=>railIslandIntegration.setPerspective('tilt'));check('快速反向切換',await p.evaluate(()=>Math.abs(M.getPitch()-55)<.01));
for(const width of [360,375,414,520,768,1280]){await p.setViewportSize({width,height:900});await p.waitForTimeout(300);await p.evaluate(()=>M.raw.jumpTo({zoom:19,pitch:55,bearing:0}));await p.waitForTimeout(450);check(width+' 放大車頭仍在畫面',await p.evaluate(()=>{const r=railIslandIntegration.renderer,q=r.frontScreen(),cv=r.map.getCanvas();return q&&q.x>0&&q.y>0&&q.x<cv.clientWidth&&q.y<cv.clientHeight;}));
await p.tap('#viewSettingsBtn');await p.tap('.view-tabs [data-view=places]');await p.locator('#riGuideGo').scrollIntoViewIfNeeded();await p.waitForTimeout(250);
const layout=await p.evaluate(()=>{const els=[...document.querySelectorAll('#riGuideRow select,#riGuideRow button')],all=[...document.querySelectorAll('button,a,input,select,[role="button"]')],overlaps=[],hits=[];for(const e of els){const r=e.getBoundingClientRect(),hit=document.elementFromPoint((r.left+r.right)/2,(r.top+r.bottom)/2);hits.push(e===hit||e.contains(hit));for(const o of all){if(o===e||o.contains(e)||e.contains(o)||o.closest('#riGuideRow'))continue;const q=o.getBoundingClientRect(),s=getComputedStyle(o);if(!q.width||!q.height||s.visibility==='hidden'||s.display==='none'||Number(s.opacity)<.5)continue;let hidden=false;for(let a=o.parentElement;a;a=a.parentElement){const c=getComputedStyle(a);if(c.visibility==='hidden'||c.display==='none'||Number(c.opacity)<.5){hidden=true;break;}}if(hidden)continue;const centerHit=document.elementFromPoint((q.left+q.right)/2,(q.top+q.bottom)/2);if(!o.closest('#viewSettingsPanel')&&centerHit!==o&&!o.contains(centerHit))continue;if(Math.min(r.right,q.right)-Math.max(r.left,q.left)>1&&Math.min(r.bottom,q.bottom)-Math.max(r.top,q.top)>1)overlaps.push(o.id||o.className);}}return {hits,overlaps,overflow:document.documentElement.scrollWidth>innerWidth+1};});check(width+' 導覽控件可點、不重疊、不溢出',layout.hits.every(Boolean)&&!layout.overlaps.length&&!layout.overflow,layout);
await p.selectOption('#riGuidePlace','taipei101');await p.tap('#riGuideGo');await p.waitForFunction(()=>railIslandIntegration.guide.current?.status==='ready',null,{timeout:15000});await p.waitForTimeout(400);check(width+' 地標導覽完成',await p.evaluate(()=>railIslandIntegration.guide.current.key==='taipei101'&&!state.followLock&&M.getPitch()>50));
await p.evaluate(()=>{const ri=railIslandIntegration,v=ri.capture().vehicles.find(v=>v.publicLabel==='117'&&v.systemId==='tra_sched');ri.select(v.id);});await p.waitForTimeout(300);
}
for(const key of ['taipeistation','tower85']){await p.evaluate(key=>railIslandIntegration.guide.goTo(key),key);check('導覽 '+key,await p.evaluate(key=>railIslandIntegration.guide.current?.key===key&&railIslandIntegration.guide.current.status==='ready',key));}
await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>railIslandIntegration.setPerspective('flat'));check('減少動態效果',await p.evaluate(()=>M.getPitch()===0));check('無前端例外',!errors.length&&await p.evaluate(()=>!railIslandIntegration.errors.length),errors);
await p.screenshot({path:out+'/'+engine+'.png'});
}catch(e){check('完成驗證',false,e.stack);if(page)console.log('STATE',await page.evaluate(()=>({build:typeof BUILD!=='undefined'?BUILD:null,ready:typeof state!=='undefined'?state.ready:null,hidden:document.hidden,follow:typeof state!=='undefined'?state.followTrain?.train:null,ri:window.railIslandIntegration?{loading:railIslandIntegration.loading,active:railIslandIntegration.active,errors:railIslandIntegration.errors,stats:railIslandIntegration.renderer?.stats,view:railIslandIntegration.renderer?.getView()}:null})).catch(e=>String(e)))}finally{await b.close();await writeFile(out+'/'+engine+'.json',JSON.stringify({passed:rows.filter(r=>r.pass).length,total:rows.length,rows},null,2));process.exitCode=rows.every(r=>r.pass)?0:1;}
