import fs from 'node:fs';import {chromium,webkit} from 'playwright';import sharp from 'sharp';
const base=process.env.BASE_URL||'http://127.0.0.1:5233/',out='output/rail-levels';fs.mkdirSync(out,{recursive:true});const rows=[],fixture=JSON.parse(fs.readFileSync('scripts/fixtures/physical-taipei-0908.json'));
for(const [engine,type]of Object.entries({chromium,webkit})){const browser=await type.launch(),page=await browser.newPage({viewport:{width:1280,height:900},locale:'zh-TW'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));
try{await page.goto(base+'?scene=3d&map=landscape&g=all&t=08:00');await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&railIslandIntegration.renderer,null,{timeout:90000});
await page.evaluate(async fixture=>{state.playing=false;clearFollow();clearFreqFollow();window.__savedRender=railIslandIntegration.render;railIslandIntegration.render=()=>{};window.__levelFrame=railIslandIntegration.capture();window.__metroPack=await(await fetch('rail-3d/physical/metro-network.json')).json();window.__levelFixture=fixture;},fixture);
for(const [station,keys]of [['台北車站',['mrt:R','mrt:BL']],['板橋',['mrt:BL','mrt:Y']],['南港',['mrt:BL']],['高雄車站',['krtc:KR']],['左營',['krtc:KR']],['高鐵臺中站',['tmrt:TG']],['忠孝復興',['mrt:BR','mrt:BL']]]){
if(process.env.FOLLOW_ONLY)continue;
await page.evaluate(({station,keys})=>{const vehicles=[];for(const key of keys)for(const dir of [1,-1]){const record=__metroPack.routes[key+':'+dir],route=railIslandPhysical.metro.geometry.route(record.pathIds,key.split(':')[0],'#d34545',{prefixM:160,suffixM:160}),ix=record.stationNames.indexOf(station),s=route.offsets[ix],coordinate=route.path.at(s).coordinate;vehicles.push({id:key+':'+dir,systemId:key.split(':')[0],routeId:key.split(':')[1],longitude:coordinate[0],latitude:coordinate[1],route,chainageM:s,railDirection:1,sourceKind:'timetable',followed:false,color:'#d34545'});}
if(station==='台北車站')for(const v of __levelFixture.vehicles.filter(v=>v.systemId.endsWith('_sched')))vehicles.push({...v,route:railIslandPhysical.geometry.route(v.pathIds,v.systemId,v.color,v.extension),followed:false});
const center=[vehicles[0].longitude,vehicles[0].latitude];window.__levelVehicles=vehicles;window.__levelUpdate=(enabled=true)=>railIslandIntegration.renderer.update({...__levelFrame,vehicles,routes:vehicles.map(v=>v.route),display:{...__levelFrame.display,enabled,modelMode:'all'},followLock:false,selectedVehicleId:null});railIslandIntegration.renderer.map.jumpTo({center,zoom:17,pitch:55,bearing:15});__levelFrame=railIslandIntegration.capture();__levelUpdate();},{station,keys});
for(const mode of ['flat','terrain']){await page.evaluate(mode=>{railIslandIntegration.renderer.setGroundMode(mode);__levelUpdate();},mode);await page.waitForFunction(()=>{__levelUpdate();return railIslandIntegration.renderer.stats.models===__levelVehicles.length;},null,{timeout:40000});await page.waitForTimeout(500);
const detail=await page.evaluate(()=>{const r=railIslandIntegration.renderer;return {poses:r.stats.poseSamples.map(p=>({id:p.id,height:p.displayHeightM,level:p.level,underground:p.underground,cars:p.cars.map(c=>({s:c.s,height:c.height,underground:c.underground,pitch:c.pitch})),expected:__levelVehicles.find(v=>v.id===p.id).route.elevation(__levelVehicles.find(v=>v.id===p.id).chainageM,r.stats.groundMode)+.65})),failures:r.stats.modelFallbacks,errors:r.stats.errors};});
const avg=key=>{const ps=detail.poses.filter(p=>p.id.startsWith(key+':'));return ps.reduce((s,p)=>s+p.height,0)/ps.length;};
const tiers=station==='台北車站'?avg('mrt:BL')-avg('mrt:R')>5&&detail.poses.every(p=>p.underground):station==='板橋'?avg('mrt:Y')-avg('mrt:BL')>5:station==='忠孝復興'?avg('mrt:BR')-avg('mrt:BL')>5:true;
rows.push({engine,station,mode,pass:tiers&&detail.poses.length>0&&!detail.failures.length&&!detail.errors.length&&detail.poses.every(p=>Math.abs(p.height-p.expected)<.03&&p.cars.every(c=>Number.isFinite(c.height)&&Number.isFinite(c.pitch))),detail});console.log(engine,station,mode,rows.at(-1).pass);
if(station==='台北車站'&&mode==='terrain'){
 const before=await page.screenshot({path:out+'/'+engine+'-taipei-underground.png'}),a=await sharp(before).removeAlpha().raw().toBuffer();await page.evaluate(()=>__levelUpdate(false));await page.waitForTimeout(200);const b=await sharp(await page.screenshot()).removeAlpha().raw().toBuffer();let changed=0;for(let i=0;i<a.length;i+=3)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>15)changed++;rows.push({engine,test:'地下半透明列車確實產生畫面像素',pass:changed>100,changed});await page.evaluate(()=>__levelUpdate(true));
}
}
}
await page.evaluate(()=>{railIslandIntegration.render=__savedRender;const frame=railIslandIntegration.capture(),v=frame.vehicles.filter(v=>v.systemId==='mrt'&&v.routeId==='R'&&v.route?.level).sort((a,b)=>Math.hypot(a.longitude-121.517,a.latitude-25.047)-Math.hypot(b.longitude-121.517,b.latitude-25.047))[0];window.__followId=v.id;M.raw.jumpTo({center:[v.longitude,v.latitude],zoom:19,pitch:55});railIslandIntegration.select(v.id);M.raw.fire('rotatestart',{originalEvent:{}});M.raw.setBearing(100);M.raw.setPitch(55);});
for(const mode of ['flat','terrain']){await page.evaluate(mode=>railIslandIntegration.setGroundMode(mode),mode);await page.waitForFunction(()=>railIslandIntegration.renderer.stats.poseSamples.some(p=>p.id===__followId&&p.underground)&&railIslandIntegration.renderer.stats.followFraming?.id===__followId,null,{timeout:30000});await page.waitForFunction(()=>{const r=railIslandIntegration.renderer;return !r.interacting&&!r.stats.followReturning&&Math.abs(r.map.getCenterElevation()-r.stats.followFraming.elevation)<.03;},null,{timeout:15000});const detail=await page.evaluate(()=>{const r=railIslandIntegration.renderer;return {selected:railIslandIntegration.capture().selectedVehicleId,expected:__followId,center:r.map.getCenterElevation(),target:r.stats.followFraming.elevation,distance:r.stats.followFraming.distanceM,expectedHeight:(()=>{const v=railIslandIntegration.capture().vehicles.find(v=>v.id===__followId),s=v.route.path.locate(r.stats.followFraming.coordinate).s;return v.route.elevation(s,r.stats.groundMode)+.65;})(),level:r.stats.poseSamples.find(p=>p.id===__followId).level};});rows.push({engine,mode,test:'地下捷運跟車鏡頭同步高度',pass:detail.selected===detail.expected&&Math.abs(detail.center-detail.target)<.1&&Math.abs(detail.target-detail.expectedHeight)<.03&&detail.distance>0&&detail.level.offsetM< -3,detail});}
for(const theme of ['light','dark']){await page.evaluate(theme=>state._setAppearance(theme),theme);await page.waitForFunction(()=>!railIslandIntegration.loading&&railIslandIntegration.renderer?.stats.undergroundModels>0,null,{timeout:45000});rows.push({engine,theme,test:'主題切換恢復地下渲染層',pass:await page.evaluate(()=>!!M.raw.getLayer('live-underground-3d')&&!railIslandIntegration.errors.length)});}
rows.push({engine,test:'無瀏覽器錯誤',pass:!errors.length,errors});
}catch(e){rows.push({engine,pass:false,error:String(e)});console.log(e);}finally{await browser.close();}}
fs.writeFileSync(process.env.RESULT_FILE||out+'/browser.json',JSON.stringify(rows,null,2));console.log({total:rows.length,failed:rows.filter(r=>!r.pass)});if(rows.some(r=>!r.pass))process.exitCode=1;
