import fs from 'node:fs';import {chromium,webkit} from 'playwright';
const base=process.env.BASE_URL||'http://127.0.0.1:5234/',rows=[],out='output/tra-binding';fs.mkdirSync(out,{recursive:true});
for(const [engine,type]of Object.entries({chromium,webkit})){const browser=await type.launch(),page=await browser.newPage({viewport:{width:1280,height:900},locale:'zh-TW'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));
try{await page.goto(base+'?g=all&scene=3d&map=landscape&t=08:00&at=25.0477,121.5171&z=18');await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&window.railIslandIntegration?.renderer?.stats.models>0,null,{timeout:90000});
const coverage=await page.evaluate(()=>{state.playing=false;const real=state.trains.filter(t=>t.sys==='tra_sched'&&!t.loop),missing=real.filter(t=>!railIslandPhysical.has(t)).map(t=>t.train),counts={};for(const tr of real){const basis=railIslandPhysical.record(tr)?.bindingBasis||'missing';counts[basis]=(counts[basis]||0)+1;}window.__realTra=real;window.__frame=railIslandIntegration.capture();window.__savedRender=railIslandIntegration.render;railIslandIntegration.render=()=>{};clearFollow();clearFreqFollow();return {total:real.length,missing,counts};});rows.push({engine,test:'當日實際班表全數對應實體股道',pass:coverage.total>800&&!coverage.missing.length,coverage});
for(const train of ['1008','1007','408','6841','6882'])for(const phase of ['departure','pass','arrival']){
const input=await page.evaluate(async({train,phase})=>{const tr=__realTra.find(t=>String(t.train)===train);if(!tr)throw Error('驗收班次不存在 '+train);const pass=tr.stops.filter(s=>s.stop===false),st=phase==='departure'?tr.stops[0]:phase==='arrival'?tr.stops.at(-1):pass[Math.floor(pass.length/2)],clock=phase==='departure'?st.depSec:st.arrSec,p=railIslandPhysical.sample(tr,clock),r=railIslandPhysical.record(tr);window.__vehicle={id:'tra-test:'+train,systemId:tr.sys,routeId:'physical',longitude:p.lon,latitude:p.lat,route:p.route,chainageM:p.chainageM,railDirection:p.railDirection,formationFacing:p.formationFacing,typeName:tr.typeName,carName:tr.carName,color:tr.color,sourceKind:'timetable'};window.__expectedCarCount=(await import('./rail-3d/integration/formations.js')).formationFor(__vehicle,'actual').lengths.length;M.raw.jumpTo({center:[p.lon,p.lat],zoom:18,pitch:55,bearing:25});window.__update=()=>railIslandIntegration.renderer.update({...__frame,vehicles:[__vehicle],routes:[p.route],display:{...__frame.display,enabled:true,modelMode:'all'},selectedVehicleId:null});return {basis:r.bindingBasis,station:st.name,clock};},{train,phase});
for(const mode of ['flat','terrain']){await page.evaluate(mode=>{railIslandIntegration.renderer.setGroundMode(mode);__update();},mode);await page.waitForFunction(()=>{__update();return window.railIslandIntegration?.renderer?.stats.models===1;},null,{timeout:30000});const detail=await page.evaluate(()=>{const r=railIslandIntegration.renderer,p=r.stats.poseSamples[0],v=__vehicle,expected=v.route.elevation(v.chainageM,r.stats.groundMode)+.65;return {id:p.id,height:p.displayHeightM,expected,cars:p.cars.length,count:__expectedCarCount,actualCarCount:p.actualCarCount,finite:p.cars.every(c=>Number.isFinite(c.height)&&Number.isFinite(c.pitch)),fallbacks:r.stats.modelFallbacks,errors:r.stats.errors};});rows.push({engine,train,phase,mode,input,pass:detail.id==='tra-test:'+train&&Math.abs(detail.height-detail.expected)<.03&&detail.cars===detail.count&&detail.finite&&!detail.fallbacks.length&&!detail.errors.length,detail});}
}
await page.screenshot({path:out+'/'+engine+'-extra-train.png'});rows.push({engine,test:'無頁面錯誤',pass:!errors.length,errors});
}catch(e){rows.push({engine,pass:false,error:String(e),detail:await page.evaluate(()=>railIslandIntegration.renderer?.stats).catch(()=>null)});}finally{await browser.close();}}
fs.writeFileSync(process.env.RESULT_FILE||out+'/browser.json',JSON.stringify(rows,null,2));console.log({total:rows.length,failed:rows.filter(r=>!r.pass)});if(rows.some(r=>!r.pass))process.exitCode=1;
