import fs from 'node:fs';import {chromium,webkit} from 'playwright';import sharp from 'sharp';
const base=process.env.BASE_URL||'http://127.0.0.1:5233/',out='output/guangci';fs.mkdirSync(out,{recursive:true});const rows=[];
for(const [engine,type]of Object.entries({chromium,webkit})){const browser=await type.launch(),page=await browser.newPage({viewport:{width:1280,height:900},locale:'zh-TW'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));
try{await page.goto(base+'?scene=3d&map=landscape&g=all&t=08:00&at=25.035,121.577&z=17');await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&railIslandIntegration.renderer,null,{timeout:90000});
await page.evaluate(()=>{state.playing=false;clearFollow();clearFreqFollow();railIslandIntegration.render=()=>{};window.__frame=railIslandIntegration.capture();window.__ln=state.decoLines.find(l=>l._sys==='mrt'&&l.id==='R');window.__place=progress=>{const vehicles=[1,-1].map(dir=>{const p=railIslandPhysical.metro.sample(__ln,{progress,lat:25.035,lon:121.577},dir);return {id:'guangci:'+dir,systemId:'mrt',routeId:'R',longitude:p.lon,latitude:p.lat,route:p.route,chainageM:p.chainageM,railDirection:1,sourceKind:'timetable',color:'#e3002c'};});window.__vehicles=vehicles;M.raw.jumpTo({center:[vehicles[0].longitude,vehicles[0].latitude],zoom:18,pitch:55,bearing:20});window.__update=()=>railIslandIntegration.renderer.update({...__frame,vehicles,routes:vehicles.map(v=>v.route),display:{...__frame.display,enabled:true,modelMode:'all'},selectedVehicleId:null});__update();};});
for(const mode of ['flat','terrain'])for(const progress of [0,.25,.5,.75,1,1.02]){await page.evaluate(({mode,progress})=>{railIslandIntegration.renderer.setGroundMode(mode);__place(progress);},{mode,progress});await page.waitForFunction(()=>{__update();return railIslandIntegration.renderer.stats.models===2;},null,{timeout:40000});await page.waitForTimeout(120);const detail=await page.evaluate(()=>{const r=railIslandIntegration.renderer;return {poses:r.stats.poseSamples.map(p=>({id:p.id,cars:p.cars.length,underground:p.underground,height:p.displayHeightM})),rails:r.stats.undergroundRailSegments,failures:r.stats.modelFallbacks,errors:r.stats.errors};});rows.push({engine,mode,progress,pass:detail.poses.length===2&&detail.poses.every(p=>p.cars===6&&p.underground&&Number.isFinite(p.height))&&detail.rails>0&&!detail.failures.length&&!detail.errors.length,detail});}
await page.evaluate(()=>__place(.5));await page.waitForTimeout(300);await page.screenshot({path:out+'/'+engine+'-both-tracks.png'});
// 獨立像素驗證：只關閉轨道，列車與底圖維持相同。
await page.evaluate(()=>{window.__testFrame={...__frame,vehicles:[],routes:__vehicles.map(v=>v.route),display:{...__frame.display,enabled:true},selectedVehicleId:null};railIslandIntegration.renderer.update(__testFrame);});await page.waitForTimeout(400);const a=await sharp(await page.screenshot()).removeAlpha().raw().toBuffer();await page.evaluate(()=>railIslandIntegration.renderer.update({...__testFrame,routes:[]}));await page.waitForTimeout(300);const b=await sharp(await page.screenshot()).removeAlpha().raw().toBuffer();let changed=0;for(let i=0;i<a.length;i+=3)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>10)changed++;rows.push({engine,test:'延伸段軌道實際產生像素',changed,pass:changed>100});
const partial=await page.evaluate(()=>{const pair=[1,-1].map(d=>railIslandPhysical.metro.routeFor(__ln,d));for(const p of pair)p.record.startIndex=1;const fallback=railIslandIntegration.capture().routes.find(r=>r.lineKey==='mrt|R'&&!r.physical);for(const p of pair)p.record.startIndex=0;return fallback?.drawingRanges;});rows.push({engine,test:'不完整股道快照保留原延伸段',pass:partial?.length===1&&partial[0][0]===0&&partial[0][1]===1468,partial});rows.push({engine,test:'無瀏覽器錯誤',pass:!errors.length,errors});
}catch(e){rows.push({engine,pass:false,error:String(e),detail:await page.evaluate(()=>({stats:railIslandIntegration.renderer?.stats,vehicles:window.__vehicles?.map(v=>({id:v.id,chainageM:v.chainageM,length:v.route.path.length})),errors:railIslandIntegration.errors})).catch(()=>null)});}finally{await browser.close();}}
fs.writeFileSync(process.env.RESULT_FILE||out+'/browser.json',JSON.stringify(rows,null,2));console.log({total:rows.length,failed:rows.filter(r=>!r.pass)});if(rows.some(r=>!r.pass))process.exitCode=1;
