// 合成遮擋物只加在驗收頁，不修改真實線形；量測不透明與透視材質下的車身像素。
import {chromium,webkit} from 'playwright';import sharp from 'sharp';import fs from 'node:fs';
const out='output/3d-integration';const results=[];fs.mkdirSync(out,{recursive:true});
for(const [name,engine]of Object.entries({chromium,webkit})){
 const browser=await engine.launch(),page=await browser.newPage({viewport:{width:1280,height:900},locale:'zh-TW'});await page.addInitScript(()=>{localStorage.setItem('trainmap-howto-seen','1');localStorage.setItem('trainmap-appearance','dark');});
 try{await page.goto((process.env.BASE_URL||'http://127.0.0.1:5207/')+'?scene=3d&g=all&train=117&t=12:00&lang=zh-TW');await page.waitForFunction(()=>railIslandIntegration.renderer&&state.followTrain,null,{timeout:60000});
 await page.evaluate(()=>{state.playing=false;setSimSec(43200);railIslandIntegration.setFormationMode('three');M.raw.setZoom(18);M.raw.setPitch(55);M.raw.fire('rotatestart',{originalEvent:{}});M.raw.setBearing(0);});await page.waitForFunction(()=>railIslandIntegration.renderer.stats.poseSamples.some(p=>p.carCount===3));await page.waitForTimeout(600);
 const clip=await page.evaluate(()=>{const r=railIslandIntegration.renderer,car=r.projectedCars().find(c=>c.index===1),el=M.getContainer().getBoundingClientRect(),b=car.bounds;return {left:Math.floor(el.left+b.left)-2,top:Math.floor(el.top+b.top)-2,width:Math.ceil(b.right-b.left)+4,height:Math.ceil(b.bottom-b.top)+4};});
 const count=async label=>{const file=out+'/'+name+'-occlusion-'+label+'.png';await page.screenshot({path:file});const {data}=await sharp(file).extract(clip).removeAlpha().raw().toBuffer({resolveWithObject:true});let n=0;for(let i=0;i<data.length;i+=3)if(data[i]>170&&data[i+1]>170&&data[i+2]>170)n++;return n;};
 const visible=await count('clear');await page.evaluate(()=>{const p=railIslandIntegration.renderer.stats.poseSamples[0].cars[1].coordinate,[x,y]=p,dx=.0005,dy=.00035;M.raw.addSource('qa-blocker',{type:'geojson',data:{type:'Feature',geometry:{type:'Polygon',coordinates:[[[x-dx,y-dy],[x+dx,y-dy],[x+dx,y+dy],[x-dx,y+dy],[x-dx,y-dy]]]},properties:{}}});M.raw.addLayer({id:'qa-blocker',type:'fill-extrusion',source:'qa-blocker',paint:{'fill-extrusion-height':20,'fill-extrusion-color':'#254872','fill-extrusion-opacity':1}},'live-vehicles-3d');});await page.waitForTimeout(500);const opaque=await count('opaque');await page.evaluate(()=>M.raw.setPaintProperty('qa-blocker','fill-extrusion-opacity',.24));await page.waitForTimeout(500);const glass=await count('glass');
 const pass=visible>20&&opaque<visible*.35&&glass>opaque+visible*.35;results.push({name,pass,visible,opaque,glass});console.log(results.at(-1));
 }catch(error){results.push({name,pass:false,error:String(error)});console.log(results.at(-1));}await browser.close();
}fs.writeFileSync(out+'/occlusion-results.json',JSON.stringify(results,null,2));if(results.some(r=>!r.pass))process.exitCode=1;
