import fs from 'node:fs';import {chromium,webkit} from 'playwright';
const base=process.env.BASE_URL||'http://127.0.0.1:5234/',out='output/head-lock',rows=[];fs.mkdirSync(out,{recursive:true});
for(const [engine,type]of Object.entries({chromium,webkit})){const browser=await type.launch();for(const width of (process.env.QUICK?[375]:[360,375,414,768])){const page=await browser.newPage({viewport:{width,height:900},isMobile:true,hasTouch:true,locale:'zh-TW'}),errors=[];page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{localStorage.setItem('trainmap-howto-seen','1');localStorage.setItem('trainmap-ambient-style','follow');});const cdp=engine==='chromium'?await page.context().newCDPSession(page):null;
const snapshot=()=>page.evaluate(()=>{const r=railIslandIntegration.renderer,b=document.getElementById('followLockBtn'),rect=b.getBoundingClientRect(),hit=document.elementFromPoint(rect.x+rect.width/2,rect.y+rect.height/2);return {lock:state.followLock,id:railIslandIntegration.capture().selectedVehicleId,center:r.map.getCenter().toArray(),zoom:r.map.getZoom(),bearing:r.map.getBearing(),error:r.stats.headLockErrorPx,models:r.stats.models,errors:r.stats.errors,overflow:document.documentElement.scrollWidth>innerWidth+1,reachable:!!hit&&b.contains(hit),rect:rect.toJSON(),pressed:b.getAttribute('aria-pressed'),tickErrors:state._tickErrs||[]};});
async function touch(type,points){if(cdp)await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map((p,i)=>({id:i+1,...p}))});else await page.evaluate(({type,points})=>{const canvas=M.raw.getCanvas(),ts=points.map((p,i)=>({identifier:i+1,target:canvas,clientX:p.x,clientY:p.y,pageX:p.x,pageY:p.y,screenX:p.x,screenY:p.y})),event=new Event({touchStart:'touchstart',touchMove:'touchmove',touchEnd:'touchend'}[type],{bubbles:true,cancelable:true});for(const [key,value]of Object.entries({touches:ts,targetTouches:ts,changedTouches:type==='touchEnd'?(window.__lastTouches||[]):ts}))Object.defineProperty(event,key,{value});canvas.dispatchEvent(event);window.__lastTouches=ts;},{type,points});}
async function gesture(kind){const x=width*.7,y=230;const points=t=>kind==='pan'?[{x:x+t*45,y:y+t*65}]:[-1,1].map(sign=>{const angle=kind==='rotate'?t*1.5:0,r=kind==='pinch'?24+t*25:30;return {x:x+sign*r*Math.cos(angle),y:y+sign*r*Math.sin(angle)};});await touch('touchStart',points(0));for(let i=1;i<=8;i++){await touch('touchMove',points(i/8));await page.waitForTimeout(60);}await touch('touchEnd',[]);await page.waitForTimeout(300);}
async function controlAudit(label){const detail=await page.evaluate(()=>{const b=document.getElementById('followLockBtn'),r=b.getBoundingClientRect(),visible=el=>{const q=el.getBoundingClientRect();if(q.width<1||q.height<1)return false;for(let n=el;n&&n instanceof Element;n=n.parentElement){const s=getComputedStyle(n);if(s.display==='none'||s.visibility==='hidden'||Number(s.opacity)===0)return false;}return true;},others=[...document.querySelectorAll('button,input,select,summary,[role="button"]')].filter(el=>el!==b&&!b.contains(el)&&visible(el)),collisions=others.filter(el=>{const q=el.getBoundingClientRect();return Math.min(r.right,q.right)-Math.max(r.left,q.left)>1&&Math.min(r.bottom,q.bottom)-Math.max(r.top,q.top)>1;}).map(el=>el.id||el.textContent.trim().slice(0,25));return {checked:others.length,collisions,visible:visible(b)};});check(label,!detail.visible||detail.collisions.length===0,detail);}
async function centered(){await page.waitForFunction(()=>{const r=window.railIslandIntegration?.renderer;if(!r)return false;return r.stats.models>0&&Number.isFinite(r.stats.headLockErrorPx)&&r.stats.headLockErrorPx<1;},null,{timeout:45000});}
function check(test,pass,detail){rows.push({engine,width,test,pass,detail});console.log(engine,width,test,pass);fs.writeFileSync(out+'/progress.json',JSON.stringify(rows,null,2));}
try{await page.goto(base+'?g=all&scene=3d&map=landscape&ground=flat&at=23.48,120.3247&z=17&t=12:00');await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&window.railIslandIntegration?.renderer,null,{timeout:90000});await page.evaluate(()=>{state.playing=false;const frame=railIslandIntegration.capture(),v=frame.vehicles.filter(v=>v.systemId==='thsr_sched'&&v.route?.physical).sort((a,b)=>Math.abs(a.latitude-23.48)-Math.abs(b.latitude-23.48))[0];railIslandIntegration.select(v.id);M.raw.jumpTo({zoom:18,pitch:50});});await centered();let a=await snapshot();check('右側鎖定開關可觸控且車頭置中',a.lock&&a.reachable&&!a.overflow&&a.rect.x>width/2&&a.pressed==='true',a);
await controlAudit('開關與所有可見操作元件不重疊');
for(const kind of ['pan','pinch','rotate']){a=await snapshot();await gesture(kind);await centered();const b=await snapshot(),change=kind==='pinch'?Math.abs(b.zoom-a.zoom)>.15:kind==='rotate'?Math.abs(b.bearing-a.bearing)>10:true;check('鎖定中 '+kind+' 保持中心且手勢有效',b.lock&&b.error<1&&change,{before:a,after:b});}
await page.locator('#followLockBtn').tap();a=await snapshot();await gesture('pan');let b=await snapshot();check('關閉後真拖曳可自由移動',!b.lock&&a.id===b.id&&Math.hypot(b.center[0]-a.center[0],b.center[1]-a.center[1])>.00002&&b.pressed==='false',{before:a,after:b});await page.locator('#followLockBtn').tap();await centered();b=await snapshot();check('重新開啟回原車頭',b.lock&&b.id===a.id&&b.error<1,b);
// 量正在行駛且手指尚未放開時的真實渲染幀，不拿更新中途的 CPU 姿態冒充畫面。
await page.evaluate(()=>{state.playing=true;state.speedMult=1;window.__pinFrames=[];window.__pinListener=()=>{const e=railIslandIntegration.renderer.stats.headLockErrorPx;if(Number.isFinite(e))__pinFrames.push(e);};M.raw.on('render',__pinListener);});await gesture('pinch');await page.waitForTimeout(300);const moving=await page.evaluate(()=>{state.playing=false;M.raw.off('render',__pinListener);return {frames:__pinFrames.length,max:Math.max(...__pinFrames),errors:__pinFrames.filter(e=>e>2)};});check('行進中捏合車頭仍固定',moving.frames>3&&moving.errors.length===0,moving);
for(const mode of ['terrain','flat']){await page.evaluate(mode=>railIslandIntegration.setGroundMode(mode),mode);await centered();b=await snapshot();check('切換地形仍鎖車頭 '+mode,b.error<1&&b.lock,b);}
await page.locator(await page.locator('#toolsFab').isVisible()?'#toolsFab':'#tabMore').tap();await controlAudit('更多抽屜展開時開關不重疊');await page.locator('#moreClose').tap();
await page.evaluate(()=>{setAmbientStyle('follow');setAmbient(true);});await centered();await page.waitForTimeout(1000);b=await snapshot();check('放空跟車保留可點的鎖定開關',b.reachable&&b.lock&&!b.overflow,b);await controlAudit('放空開關與出口、時鐘、工具列不重疊');await gesture('rotate');await centered();a=await snapshot();await page.locator('#followLockBtn').tap();await gesture('pan');await page.evaluate(()=>{state._tourNext=0;nextTourTrain();});b=await snapshot();check('放空解鎖後可移動且不換車',!b.lock&&b.id===a.id&&Math.hypot(b.center[0]-a.center[0],b.center[1]-a.center[1])>.00002,{before:a,after:b});await page.locator('#followLockBtn').tap();await centered();b=await snapshot();check('放空重新鎖定回同一班車',b.lock&&b.id===a.id&&b.error<1,b);await page.screenshot({path:out+'/'+engine+'-'+width+'-ambient.png'});
await page.evaluate(()=>setAmbient(false));await centered();b=await snapshot();check('離開放空保持可用',b.reachable&&b.lock&&!b.errors.length&&!b.tickErrors.length&&!errors.length,{...b,pageErrors:errors});
}catch(e){check('驗收流程',false,String(e));}finally{await page.close();}}await browser.close();}
fs.writeFileSync(process.env.RESULT_FILE||out+'/browser.json',JSON.stringify(rows,null,2));console.log({total:rows.length,failed:rows.filter(r=>!r.pass)});if(rows.some(r=>!r.pass))process.exitCode=1;
