import fs from 'node:fs';import {chromium,webkit} from 'playwright';const base=process.env.BASE_URL||'http://127.0.0.1:5256/',rows=[];
for(const [engine,type]of Object.entries({chromium,webkit})){const b=await type.launch();for(const width of [360,375,390,414,520,768]){const p=await b.newPage({viewport:{width,height:900},isMobile:true,hasTouch:true,locale:'zh-TW'}),errors=[];p.on('pageerror',e=>errors.push(e.message));try{
 await p.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));await p.goto(base+'?g=all&scene=3d&map=landscape&at=25.0054,121.41105&z=20&t=21:00');
 await p.waitForFunction(()=>state.ready&&railIslandIntegration?.renderer?.stats.structures.portalTracks>=2,null,{timeout:90000});await p.evaluate(()=>{state.playing=false;});
 for(const full of [false,true]){await p.evaluate(full=>{document.body.classList.toggle('fs',full);M.resize();},full);await p.locator('#tabMore').tap();await p.locator('#sunlightRow').scrollIntoViewIfNeeded();const prior=await p.evaluate(()=>railIslandSunlight.enabled);await p.tap('#sunlightRow');
 const detail=await p.evaluate(()=>{const e=document.querySelector('#sunlightRow'),r=e.getBoundingClientRect();return {enabled:railIslandSunlight.enabled,hit:e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)),height:r.height,overflow:document.documentElement.scrollWidth>innerWidth+1,vertices:railIslandIntegration.renderer.stats.structures.vertices,errors:railIslandIntegration.renderer.stats.errors};});rows.push({engine,width,full,pass:detail.enabled!==prior&&detail.hit&&detail.height>=44&&!detail.overflow&&!detail.errors.length,detail});console.log(engine,width,full,rows.at(-1).pass);await p.tap('#sunlightRow');await p.tap('#moreClose');}
 if(width===375)await p.screenshot({path:`output/portal-review/${engine}-mobile.png`,timeout:60000});rows.push({engine,width,test:'無例外',pass:!errors.length,errors});
}catch(e){rows.push({engine,width,pass:false,error:e.message});console.log(engine,width,e.message);}finally{await p.close();}}await b.close();}
fs.writeFileSync('output/portal-review/mobile.json',JSON.stringify(rows,null,2));if(rows.some(r=>!r.pass))process.exitCode=1;
