// 真實無視窗雙引擎：全班次官方時刻、實際車身與手機按播放後立即離站。
import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import {fileURLToPath} from 'node:url';import {chromium,webkit} from 'playwright';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.bin':'application/octet-stream'};
let server=null,base=process.env.BASE_URL;const expected=process.env.EXPECTED_BUILD||(await fs.readFile(path.join(root,'index.html'),'utf8')).match(/const BUILD = '([^']+)'/)[1];
if(!base){server=http.createServer(async(req,res)=>{try{const u=decodeURIComponent(new URL(req.url,'http://x').pathname),file=path.join(root,u==='/'?'index.html':u);if(u.startsWith('/api/')||path.relative(root,file).startsWith('..')){res.writeHead(404).end();return;}const b=await fs.readFile(file);res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream'}).end(b);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/';}
try{for(const [engine,type]of [['chromium',chromium],['webkit',webkit]]){const browser=await type.launch(engine==='chromium'?{channel:'chromium',headless:true}:{headless:true});try{
 const context=await browser.newContext({viewport:{width:375,height:900},isMobile:true,hasTouch:true,locale:'zh-TW'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await context.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));await page.route('**/api/**',r=>r.fulfill({status:404,body:'{}',contentType:'application/json'}));
 await page.goto(base+'?g=all&scene=3d&t=09:30&at=23.51,120.81&z=17&lang=zh-TW',{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>typeof state!=='undefined'&&state.ready&&state.trains.some(t=>t.sys==='afr_sched')&&window.railIslandPhysical&&window.railIslandIntegration?.renderer,null,{timeout:90000});assert.equal(await page.evaluate(()=>BUILD),expected);
 const all=await page.evaluate(()=>{state.playing=false;railIslandIntegration.setModelMode('all');const ts=state.trains.filter(t=>t.sys==='afr_sched');let departures=0,fallbacks=0;const failures=[];
  for(const tr of ts){const r=railIslandPhysical.record(tr);if(!r){failures.push('缺股道 '+tr.train);continue;}fallbacks+=r.afrTiming.fallbacks;for(let i=0;i<r.stops.length;i++){const s=r.stops[i];if(s.stop===false)continue;if(s.arrSec!==tr.stops[i].arrSec||s.depSec!==tr.stops[i].depSec)failures.push('改正式時刻 '+tr.train+' '+s.name);if(i===r.stops.length-1)continue;const a=trainPos(tr,s.depSec),b=trainPos(tr,s.depSec+1);if(!a?.dwell||!b||b.dwell||b.chainageM<=a.chainageM)failures.push('未準時出發 '+tr.train+' '+s.name);departures++;}}
  window.afrTimingPick=(no,dt)=>{const tr=ts.find(t=>String(t.train)===no);setSimSec(tr.stops[0].depSec+dt);const v=railIslandIntegration.capture().vehicles.find(v=>v.systemId==='afr_sched'&&v.publicLabel===no);if(!v)throw Error('列車不在畫面 '+no);railIslandIntegration.select(v.id);M.raw.jumpTo({center:[v.longitude,v.latitude],zoom:18,pitch:45});return {id:v.id,dep:tr.stops[0].depSec,coordinate:[v.longitude,v.latitude]};};
  return {trains:ts.length,departures,fallbacks,failures};});assert.equal(all.trains,52);assert.equal(all.departures,82);assert.equal(all.fallbacks,0);assert.deepEqual(all.failures,[]);
 for(const width of [360,375,414,600,768,1280]){await page.setViewportSize({width,height:900});for(const [no,dt]of [['33',1],['33',60],['32',60],['121',60]]){const p=await page.evaluate(([no,dt])=>afrTimingPick(no,dt),[no,dt]);await page.waitForFunction(p=>railIslandIntegration.renderer.stats.poseSamples.some(v=>v.id===p.id&&Math.abs(v.coordinate[0]-p.coordinate[0])<1e-8&&Math.abs(v.coordinate[1]-p.coordinate[1])<1e-8),p,{timeout:30000});const body=await page.evaluate(id=>{const s=railIslandIntegration.renderer.stats.poseSamples.find(v=>v.id===id);return {cars:s.cars.length,finite:s.cars.every(c=>c.coordinate.every(Number.isFinite)&&Number.isFinite(c.height)),offset:s.avoidanceOffsetM||0};},p.id);assert.equal(body.cars,6);assert(body.finite);assert.equal(body.offset,0);}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);console.log(JSON.stringify({engine,width,...all}));}
 await page.setViewportSize({width:375,height:900});const pick=await page.evaluate(()=>{state.playing=false;setSpeed(10);return afrTimingPick('33',-1);});if(!await page.locator('#pp').isVisible())await page.tap('.controls');await page.tap('#pp');assert(await page.evaluate(()=>state.playing));
 const animation=await page.evaluate(async p=>{const frames=[];await new Promise((resolve,reject)=>{const until=performance.now()+20000;function step(){const v=railIslandIntegration.capture().vehicles.find(v=>v.id===p.id);if(v)frames.push({t:state.simSec,lat:v.latitude,lon:v.longitude});if(state.simSec>=p.dep+30){state.playing=false;resolve();return;}if(performance.now()>until){reject(Error('播放未完成'));return;}requestAnimationFrame(step);}requestAnimationFrame(step);});let travel=0,maxStep=0;for(let i=1;i<frames.length;i++){const d=haversineKm(frames[i-1],frames[i])*1000;travel+=d;maxStep=Math.max(maxStep,d);}const start=frames[0],early=frames.find(f=>f.t>=p.dep+5);return {frames:frames.length,travel,maxStep,earlyTravel:early?haversineKm(start,early)*1000:0};},pick);
 assert(animation.frames>10&&animation.travel>40&&animation.maxStep<30&&animation.earlyTravel>1,JSON.stringify(animation));console.log(JSON.stringify({engine,touchPlayback:animation}));
 const flat=await page.evaluate(()=>{railIslandIntegration.setMode(false);const tr=state.trains.find(t=>t.sys==='afr_sched'&&String(t.train)==='33'),t=tr.stops[0].depSec,a=trainPos(tr,t),b=trainPos(tr,t+5);return {dwell:b.dwell,travel:haversineKm(a,b)*1000,delay:liveDelaySec(tr)};});assert.equal(flat.dwell,false);assert(flat.travel>1);assert.equal(flat.delay,0);assert.deepEqual(errors,[]);await context.close();
 }finally{await browser.close();}}}finally{server?.close();}
console.log('林鐵準時發車瀏覽器驗收通過：雙引擎、六種寬度、順逆向車身與手機觸控播放');
