// 用實際班表與 renderer 驗林鐵推／拉方向；首段方向、折返連續性、雙引擎及手機觸控。
// 埠預設 0（系統挑空埠）並綁 127.0.0.1：寫死 5686 又不給 host 時，別棵樹留下的孤兒佔著 127.0.0.1:5686，這裡綁 :: 照樣成功、請求卻被孤兒接走（2026-09-25 實測）。
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {chromium,webkit} from 'playwright';
const root=process.cwd(),port=Number(process.env.PORT||0),out=process.env.OUT||'output/afr-push-pull';fs.mkdirSync(out,{recursive:true});
const server=createServer((req,res)=>{const u=new URL(req.url,'http://x');let f=path.join(root,decodeURIComponent(u.pathname));if(u.pathname.startsWith('/api/')){res.setHeader('content-type','application/json');return res.end(u.pathname==='/api/thsr-schedule'?fs.readFileSync('data/thsr_schedule_dense.json'):'{}');}if(!fs.existsSync(f)){res.statusCode=404;return res.end();}if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('content-type',({'.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.png':'image/png'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});await new Promise(r=>server.listen(port,'127.0.0.1',r));
// 預期方向獨立列出，不能從受測函式或車次奇偶產生答案。-1＝機車在行進後端。
const cases=[['1','嘉義',-1],['2','十字路',1],['5','屏遮那',-1],['5','第一分道',1],['5','第二分道',-1],['5','神木',1],['8','阿里山',-1],['8','神木',1],['8','第二分道',-1],['8','第一分道',1],['31','阿里山',-1],['32','沼平',1],['120','阿里山',-1],['121','神木',1],['97','阿里山',-1],['98','祝山',1]];
const rows=[];
async function open(browser,options={}){
 const page=await browser.newPage({viewport:{width:1280,height:900},locale:'zh-TW',...options});await page.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));await page.clock.install({time:new Date('2026-09-13T12:00:00+08:00')});
 if(process.env.MUTATE==='initial')await page.route('**/rail-3d/physical/afr-operation.js',r=>r.fulfill({contentType:'text/javascript',body:'export function afrInitialFacing(){return 1;}'}));
 await page.goto(`http://127.0.0.1:${server.address().port}/?scene=3d&g=all&at=23.51,120.81&z=17&t=09:02`);await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&window.railIslandIntegration?.renderer,null,{timeout:180000});await page.clock.pauseAt(new Date('2026-09-13T12:01:00+08:00'));
 await page.evaluate(()=>{state.playing=false;_blockHold.clear();updateBlockHolds=()=>{};railIslandIntegration.setModelMode('all');});return page;
}
async function show(page,no,station){
 const point=await page.evaluate(([no,station])=>{const tr=state.trains.find(t=>t.sys==='afr_sched'&&String(t.train)===no),i=tr.stops.findIndex(s=>s.name===station);if(i<0||!tr.stops[i+1])throw Error('案例缺站');const t=Math.round((tr.stops[i].depSec+tr.stops[i+1].arrSec)/2);setSimSec(t);const p=trainPos(tr,t);if(!p?.physical)throw Error('案例沒有使用實體路徑');M.raw.jumpTo({center:[p.lon,p.lat],zoom:18.5,pitch:45,bearing:0});railIslandIntegration.render();return{no,station,t,facing:p.formationFacing,centre:[p.lon,p.lat],s:p.chainageM};},[no,station]);
 await page.waitForFunction(no=>{railIslandIntegration.render();return railIslandIntegration.renderer.stats.poseSamples.some(p=>p.id.startsWith('afr_sched:')&&p.id.split(':')[2]===no);},no,{timeout:60000});await page.clock.runFor(500);
 const model=await page.evaluate(no=>railIslandIntegration.renderer.stats.poseSamples.find(p=>p.id.startsWith('afr_sched:')&&p.id.split(':')[2]===no),no);assert(model&&model.modelId==='dl25');assert.equal(model.carCount,6);assert.equal(model.actualCarCount,6);assert.equal(model.countBasis,'estimated');assert.equal(Math.sign(model.cars[0].s-model.cars.at(-1).s),point.facing,'實際 renderer 機車與客車順序');return{...point,firstS:model.cars[0].s,lastS:model.cars.at(-1).s,model:model.modelId};
}
try{for(const[engine,type]of Object.entries(process.env.ENGINE?{[process.env.ENGINE]:{chromium,webkit}[process.env.ENGINE]}:{chromium,webkit})){
 const browser=await type.launch();try{const page=await open(browser),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const coverage=await page.evaluate(async()=>{const {afrInitialFacing}=await import('/rail-3d/physical/afr-operation.js'),{formationPoses,distanceM}=await import('/rail-3d/integration/train-path.js'),F=await import('/rail-3d/integration/formations.js'),catalog=await(await fetch('/rail-3d/assets/blender-map-v1/manifest.json')).json(),parts=F.assembleFormation(F.formationFor({systemId:'afr_sched'}),catalog).parts;
 const trains=state.trains.filter(t=>t.sys==='afr_sched');let samples=0,maxJump=0,turns=0,poseCheckedTurns=0,existingMissing=0,existingClipped=0;const fails=[];
 for(const tr of trains){const r=railIslandPhysical.record(tr);if(!r||afrInitialFacing(tr)==null){fails.push('沒有依據或路徑 '+tr.train);continue;}for(let t=tr.stops[0].depSec;t<tr.stops.at(-1).arrSec;t+=30){const p=trainPosAt(tr,t),f=r.initialFacing;r.initialFacing=1;const old=trainPosAt(tr,t);r.initialFacing=f;if(!!p!==!!old){fails.push('位置出現狀態改變 '+tr.train);break;}if(!p){existingMissing++;continue;}if(!p.physical||p.lat!==old.lat||p.lon!==old.lon){fails.push('改變中心位置 '+tr.train);break;}const poses=formationPoses(p.route.path,p.chainageM,p.formationFacing,parts),before=formationPoses(old.route.path,old.chainageM,old.formationFacing,parts);if(!!poses!==!!before){fails.push('車身出現狀態改變 '+tr.train);break;}if(!poses){existingClipped++;continue;}samples++;}
 // 整列每節車在實際折返點進出時應留在原地；不能僅驗列車中心。
 for(const i of r.reversals){const t=r.schedule[i].arrSec,a=trainPosAt(tr,t-.001),b=trainPosAt(tr,t+.001);if(!a||!b){fails.push('折返缺失');continue;}if(a.formationFacing!==-b.formationFacing)fails.push('折返未交換前後端 '+tr.train);turns++;const pa=formationPoses(a.route.path,a.chainageM,a.formationFacing,parts),pb=formationPoses(b.route.path,b.chainageM,b.formationFacing,parts);if(!pa||!pb){const ca=formationPoses(a.route.path,a.chainageM,a.formationFacing*r.initialFacing,parts),cb=formationPoses(b.route.path,b.chainageM,b.formationFacing*r.initialFacing,parts);if(!!ca!==!!pa||!!cb!==!!pb)fails.push('折返新增裁切');existingClipped++;continue;}for(let j=0;j<pa.length;j++)maxJump=Math.max(maxJump,distanceM(pa[j].coordinate,pb[j].coordinate));poseCheckedTurns++;}}
 return{trains:trains.length,samples,maxJump,turns,poseCheckedTurns,existingMissing,existingClipped,fails};});assert.equal(coverage.trains,52);assert.deepEqual(coverage.fails,[]);assert.equal(coverage.turns,6);assert(coverage.poseCheckedTurns>=4);assert(coverage.maxJump<1);rows.push({engine,coverage});
 for(const[no,station,expected]of cases){const r=await show(page,no,station);assert.equal(r.facing,expected,`${no} ${station} 推拉相反`);rows.push({engine,...r});if(['31','32','120','121'].includes(no)){await page.clock.runFor(1000);await page.screenshot({path:`${out}/${engine}-${no}.png`});}}
 // 近景相機必須朝實際機車那端取景，含車尾推進；用車身實際里程獨立比對。
 for(const[no,station]of [['31','阿里山'],['32','沼平']]){
  await show(page,no,station);await page.evaluate(no=>{const ri=railIslandIntegration,v=ri.capture().vehicles.find(v=>v.systemId==='afr_sched'&&v.publicLabel===no);ri.select(v.id);M.raw.jumpTo({zoom:21,pitch:0,bearing:0});},no);await page.clock.runFor(1200);
  const framing=await page.evaluate(no=>{const ri=railIslandIntegration,r=ri.renderer,v=ri.capture().vehicles.find(v=>v.systemId==='afr_sched'&&v.publicLabel===no),pose=r.stats.poseSamples.find(p=>p.id===v.id),f=r.stats.followFraming,anchor=v.route.path.locate([v.longitude,v.latitude],v.chainageM),focus=v.route.path.locate(f.coordinate,anchor.s),front=r.frontScreen(),canvas=r.map.getCanvas();return {no,distance:f.distanceM,delta:focus.s-anchor.s,headDelta:pose.cars[0].s-pose.cars.at(-1).s,front,visible:front&&front.x>0&&front.y>0&&front.x<canvas.clientWidth&&front.y<canvas.clientHeight};},no);
  assert(framing.distance>0,'近景有啟用取景');assert.equal(Math.sign(framing.delta),Math.sign(framing.headDelta),'取景朝實際機車那端');assert(framing.visible,'機車仍在畫面');rows.push({engine,framing});
 }
 assert.equal(errors.length,0,errors.join(' | '));await page.close();
 for(const width of[360,375,414,768]){const p=await open(browser,{viewport:{width,height:900},isMobile:true,hasTouch:true});const r=await show(p,'31','阿里山');assert.equal(r.facing,-1);await p.waitForFunction(()=>window.railViewControls);await p.locator('#viewSettingsBtn').tap();await p.locator('.view-tabs [data-view=map]').tap();const button=p.locator('[data-rail3d="ground"] [data-value="terrain"]');await button.scrollIntoViewIfNeeded();assert(await button.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));await button.tap();await p.locator('.view-close').tap();await p.waitForFunction(()=>railIslandIntegration.renderer.stats.groundMode==='terrain');await p.clock.runFor(500);const q=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,errors:railIslandIntegration.renderer.stats.errors}));assert(!q.overflow);assert.deepEqual(q.errors,[]);rows.push({engine,width,touch:true,...q});await p.close();}
 }finally{await browser.close();}}
}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(rows,null,2));server.close();}console.log(JSON.stringify(rows,null,2));
