// 真引擎逐秒對照局部派軌，並看實際 renderer 的車廂與手機觸控。長編組只透過受測頁路由注入。
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {chromium,webkit} from 'playwright';
const root=process.cwd(),port=Number(process.env.PORT||5644),out='output/verified-station-browser';fs.mkdirSync(out,{recursive:true});
const server=createServer((req,res)=>{const u=new URL(req.url,'http://x');let f=path.join(root,decodeURIComponent(u.pathname));if(u.pathname.startsWith('/api/')){res.setHeader('content-type','application/json');return res.end(u.pathname==='/api/thsr-schedule'?fs.readFileSync('data/thsr_schedule_dense.json'):'{}');}if(!fs.existsSync(f)){res.statusCode=404;return res.end();}if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('content-type',({'.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.png':'image/png'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});await new Promise(r=>server.listen(port,r));
const cases=[['411','162',24240],['301','306',32160],['2608','2523',44880],['5899','410',46440],['410','423',46485],['5899','423',46560],['3028','431',52920],['5898','431',53040],['1208','129',53040],['4234','231',67320],['3021','432',71760]];
const rows=[];
try{for(const[engine,type]of Object.entries({chromium,webkit})){
 const browser=await type.launch();try{const ctx=await browser.newContext({viewport:{width:1280,height:900},locale:'zh-TW'});await ctx.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-12T12:00:00+08:00'));
 await page.route('**/*tra-live*',r=>r.abort());await page.route('**/api/delay-stats*',r=>r.abort());
 const formation=fs.readFileSync('rail-3d/integration/formations.js','utf8').replace("commuter:unknown('emu800',repeat(3,20),2.9)","commuter:estimated('emu800',repeat(8,20),2.9,'推估 8 節')").replace("chukuang:unknown('e200',[17,20,20],2.9)","chukuang:estimated('e200',[17,...repeat(8,20)],2.9,'推估 9 節')");
 await page.route('**/rail-3d/integration/formations.js',r=>r.fulfill({contentType:'text/javascript',body:formation}));
 await page.goto(`http://127.0.0.1:${port}/?scene=3d&g=all&at=22.619,121.0047&z=17&t=08:56`);await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&window.railIslandIntegration?.renderer,null,{timeout:180000});
 const setup=await page.evaluate(async()=>{
  state.playing=false;_blockHold.clear();updateBlockHolds=()=>{}; // 無 hold 對照證明是換股道，而非把車藏到別個時間。
  const[{createPhysicalMotion},F,net,dispatch,proof,catalog]=await Promise.all([import('/rail-3d/physical/motion.js'),import('/rail-3d/integration/formations.js'),fetch('/rail-3d/physical/network.json').then(r=>r.json()),fetch('/rail-3d/physical/dispatch.json').then(r=>r.json()),fetch('/scripts/fixtures/physical-route-conflicts-0912.json').then(r=>r.json()),fetch('/rail-3d/assets/blender-map-v1/manifest.json').then(r=>r.json())]);
  const before=createPhysicalMotion(net,null,{...dispatch,plans:{...dispatch.plans,...proof.beforePlans}}),trains=state.trains.filter(t=>t.sys==='tra_sched'&&!t.loop&&!t.stops._prevNight),models=new WeakMap();
  const model=tr=>{if(!models.has(tr)){const sp=specialOf(tr);models.set(tr,F.assembleFormation(F.formationFor({systemId:tr.sys,carName:tr.carName,stockId:sp?.stock?.id,branchId:sp?.branch?.id,namedId:sp?.named?.id},'actual'),catalog));}return models.get(tr);};
  // 以來源節點對為鍵、正規化方向的區間交集；同一長 edge 上不同位置不算互穿。
  const footprint=(p,len)=>{const m=new Map(),d=p.route.path.d;for(let i=0;i<p.route.edges.length;i++){const a=Math.max(d[i],p.chainageM-len/2),b=Math.min(d[i+1],p.chainageM+len/2);if(b<=a)continue;const edge=p.route.edges[i],forward=p.route.nodeIds[i]<p.route.nodeIds[i+1],u=(a-d[i])/(d[i+1]-d[i]),v=(b-d[i])/(d[i+1]-d[i]);m.set(edge.resource,{lo:forward?u:1-v,hi:forward?v:1-u,len:d[i+1]-d[i]});}return m;};
  const overlap=(a,b)=>{let n=0;for(const[k,x]of a){const y=b.get(k);if(y)n+=Math.max(0,Math.min(x.hi,y.hi)-Math.max(x.lo,y.lo))*x.len;}return n;};
  window.__routeProbe=(a,b,t)=>{const ta=trains.find(tr=>String(tr.train)===a),tb=trains.find(tr=>String(tr.train)===b);if(!ta||!tb)throw Error('案例缺車');const pa=trainPosAt(ta,t),pb=trainPosAt(tb,t),oa=before.sample(ta,t,{wrap:schedWrapT}),ob=before.sample(tb,t,{wrap:schedWrapT});if(!pa||!pb||!oa||!ob)throw Error('案例列車未出現');return {before:overlap(footprint(oa,model(ta).lengthM),footprint(ob,model(tb).lengthM)),after:overlap(footprint(pa,model(ta).lengthM),footprint(pb,model(tb).lengthM)),models:[model(ta).id,model(tb).id],lengths:[model(ta).lengthM,model(tb).lengthM]};};
  railIslandIntegration.setModelMode('all');return {trains:trains.length};
 });assert(setup.trains>=800);
 for(const[a,b,t]of cases){
  const stats=await page.evaluate(([a,b,t])=>{let before=0,after=0,added=0;const centre=__routeProbe(a,b,t);for(let s=t-30;s<=t+30;s++){const r=__routeProbe(a,b,s);if(r.before>.01)before++;if(r.after>.01)after++;if(r.after>.01&&r.before<=.01)added++;}return {centre,beforeSeconds:before,afterSeconds:after,addedSeconds:added};},[a,b,t]);
  assert(stats.centre.before>.01,`${a}/${b} 對照組沒有重現`);assert(stats.centre.after<.01,`${a}/${b} 修復時點仍互穿`);assert(stats.addedSeconds===0&&stats.afterSeconds<stats.beforeSeconds,`${a}/${b} 一分鐘窗未改善`);
  await page.evaluate(([no,t])=>{setSimSec(t);const tr=state.trains.find(t=>t.sys==='tra_sched'&&String(t.train)===no),p=trainPos(tr,t);M.raw.jumpTo({center:[p.lon,p.lat],zoom:17,pitch:45,bearing:0});railIslandIntegration.render();},[a,t]);
  await page.waitForFunction(pair=>{railIslandIntegration.render();return pair.every(no=>railIslandIntegration.renderer.stats.poseSamples.some(p=>p.id.split(':')[2]===no));},[a,b],{timeout:60000});
  const drawn=await page.evaluate(pair=>railIslandIntegration.renderer.stats.poseSamples.filter(p=>pair.includes(p.id.split(':')[2])).map(p=>({train:p.id.split(':')[2],model:p.modelId,cars:p.carCount,length:p.lengthM})),[a,b]);assert.equal(drawn.length,2);for(const r of drawn){const ix=r.train===a?0:1;assert(Math.abs(r.length-stats.centre.lengths[ix])<1e-6);}
  rows.push({engine,a,b,t,...stats,drawn});console.log(JSON.stringify(rows.at(-1)));
  if(a==='301'||a==='1208')await page.screenshot({path:`${out}/${engine}-${a}-${b}.png`});
 }
 // 兩分鐘取樣漏掉的 30 秒三車同停，必須另外驗到；這次新增第三股道後也要分開。
 const residual=await page.evaluate(()=>__routeProbe('410','423',46485));assert(residual.before>200&&residual.after<.01);rows.push({engine,threeTrainMeet:'12:54:30–12:55:00 太麻里 410/423/5899',...residual});assert.equal(errors.length,0,errors.join('\n'));await ctx.close();
 // 手機既有操作在新股道場景仍可觸及；兩個地形模式都真的以 touch 切換。
 for(const width of[360,375,414,768]){const page=await browser.newPage({viewport:{width,height:900},isMobile:true,hasTouch:true,locale:'zh-TW'});await page.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));await page.clock.setFixedTime(new Date('2026-09-12T12:00:00+08:00'));await page.goto(`http://127.0.0.1:${port}/?scene=3d&g=all&at=22.619,121.0047&z=17&t=08:56`);await page.waitForFunction(()=>state.ready&&window.railIslandIntegration?.renderer?.stats.poseSamples?.length>0,null,{timeout:180000});await page.evaluate(()=>{state.playing=false;setSimSec(32160);});
  for(const mode of['flat','terrain']){await page.locator(await page.locator('#toolsFab').isVisible()?'#toolsFab':'#tabMore').tap();const button=page.locator('[data-rail3d="ground"] [data-value="'+mode+'"]');await button.scrollIntoViewIfNeeded();assert(await button.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));await button.tap();await page.locator('#moreClose').tap();await page.waitForFunction(mode=>railIslandIntegration.renderer.stats.groundMode===mode,mode);}
  const stats=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,errors:railIslandIntegration.renderer.stats.errors,models:railIslandIntegration.renderer.stats.poseSamples.map(p=>({id:p.id,length:p.lengthM}))}));assert(!stats.overflow);assert.equal(stats.errors.length,0);rows.push({engine,width,touch:true,...stats});await page.close();}
 }finally{await browser.close();}}
}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(rows,null,2));server.close();}
