// 控制組：同 XY 的異色車體，上層實心、下層透視。這是渲染 fixture，不是派車或地理資料。
import fs from 'node:fs';import {chromium,webkit} from 'playwright';import sharp from 'sharp';
const base=process.env.BASE_URL||'http://127.0.0.1:5233/',rows=[];fs.mkdirSync('output/rail-levels',{recursive:true});
for(const [engine,type]of Object.entries({chromium,webkit})){const browser=await type.launch(),page=await browser.newPage({viewport:{width:1280,height:900},locale:'zh-TW'});await page.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));
try{await page.goto(base+'?scene=3d&g=all&ground=flat&t=08:00');await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&window.railIslandIntegration?.renderer,null,{timeout:90000});await page.evaluate(async()=>{const {makePath}=await import('/rail-3d/integration/train-path.js'),pack=await(await fetch('rail-3d/physical/metro-network.json')).json(),r=railIslandPhysical.metro.geometry.route(pack.routes['mrt:BR:1'].pathIds,'mrt','#dd8844',{prefixM:150,suffixM:150}),s=2000,coord=r.path.at(s).coordinate,frame=railIslandIntegration.capture();state.playing=false;clearFollow();clearFreqFollow();railIslandIntegration.render=()=>{};const make=(id,routeId,z)=>({id,routeId,systemId:'mrt',longitude:coord[0],latitude:coord[1],railDirection:1,chainageM:s,route:{...r,path:makePath(r.coordinates),elevation:()=>z,level:()=>({kind:z<0?'tunnel':'bridge',offsetM:z,layer:z<0?-2:1})}});window.__depthVehicles=[make('upper','BR',12),make('lower','R',-16)];window.__depthUpdate=(which)=>{const vehicles=which==='both'?__depthVehicles:which==='upper'?[__depthVehicles[0]]:[];railIslandIntegration.renderer.update({...frame,vehicles,routes:[],display:{...frame.display,modelMode:'all',enabled:true},followLock:false,selectedVehicleId:null});};M.raw.jumpTo({center:coord,zoom:20,pitch:0,bearing:0});__depthUpdate('both');});await page.waitForFunction(()=>{__depthUpdate('both');return window.railIslandIntegration?.renderer?.stats.models===2;});await page.waitForTimeout(400);
const raw=async()=>sharp(await page.screenshot()).removeAlpha().raw().toBuffer();const both=await raw();await page.screenshot({path:'output/rail-levels/'+engine+'-vehicle-depth.png'});await page.evaluate(()=>__depthUpdate('upper'));await page.waitForTimeout(200);const upper=await raw();await page.evaluate(()=>__depthUpdate('none'));await page.waitForTimeout(200);const none=await raw();
let solid=0,corrupted=0;const dist=(a,b,i)=>Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2]);for(let y=200;y<750;y++)for(let x=350;x<1050;x++){const i=(y*1280+x)*3;if(dist(upper,none,i)>100){solid++;if(dist(both,upper,i)>30)corrupted++;}}
rows.push({engine,pass:solid>200&&corrupted/solid<.02,solid,corrupted,ratio:corrupted/solid});console.log(rows.at(-1));
}catch(e){rows.push({engine,pass:false,error:String(e)});console.log(e);}finally{await browser.close();}}
fs.writeFileSync('output/rail-levels/occlusion.json',JSON.stringify(rows,null,2));if(rows.some(r=>!r.pass))process.exitCode=1;
