import fs from 'node:fs';import {chromium,webkit} from 'playwright';import {createRequire} from 'node:module';const {PNG}=createRequire(import.meta.url)('playwright-core/lib/utilsBundle');
const base=process.env.BASE_URL||'http://127.0.0.1:5234/',out='output/rail-structures',rows=[];fs.mkdirSync(out,{recursive:true});
for(const [engine,type]of Object.entries({chromium,webkit})){const browser=await type.launch();for(const width of (process.env.QUICK?[1280]:[1280,360,375,414,768])){const mobile=width<1000,page=await browser.newPage({viewport:{width,height:900},isMobile:mobile,hasTouch:mobile,locale:'zh-TW'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));
try{await page.goto(base+'?g=all&scene=3d&map=landscape&at=23.48,120.3247&z=17&t=12:00');await page.waitForFunction(()=>state.ready&&window.railIslandPhysical&&railIslandIntegration.renderer?.stats.structures?.piers>0,null,{timeout:90000});
await page.evaluate(()=>{state.playing=false;clearFollow();clearFreqFollow();window.__bridgeFrame=railIslandIntegration.capture();window.__bridgeRender=railIslandIntegration.render;railIslandIntegration.render=()=>{};window.__bridgeUpdate=(show=true,vehicles=[])=>railIslandIntegration.renderer.update({...__bridgeFrame,routes:show?__bridgeFrame.routes:[],vehicles,display:{...__bridgeFrame.display,enabled:true,modelMode:'all'},followLock:false,selectedVehicleId:null});});
for(const mode of ['flat','terrain']){
if(mobile){await page.locator(await page.locator('#toolsFab').isVisible()?'#toolsFab':'#tabMore').tap();const target=page.locator('[data-rail3d="ground"] [data-value="'+mode+'"]');await target.scrollIntoViewIfNeeded();await target.tap();await page.locator('#moreClose').tap();}else await page.evaluate(mode=>railIslandIntegration.renderer.setGroundMode(mode),mode);
await page.evaluate(()=>{railIslandIntegration.renderer.map.jumpTo({center:[120.3247,23.48],zoom:18.2,pitch:68,bearing:65});__bridgeUpdate();});
await page.waitForFunction(mode=>{__bridgeUpdate();const r=railIslandIntegration.renderer,s=r.stats.structures;return s.piers>3&&s.samples.every(p=>Math.abs(p.groundM-(mode==='flat'?0:r.map.queryTerrainElevation(p.coordinate)))<.01);},mode,{timeout:60000});await page.waitForTimeout(700);
const detail=await page.evaluate(()=>{const r=railIslandIntegration.renderer,rect=r.map.getCanvas().getBoundingClientRect();return {stats:structuredClone(r.stats.structures),errors:r.stats.errors,overflow:document.documentElement.scrollWidth>innerWidth+1,spots:r.stats.structures.samples.map(p=>{const s=r.projectCoordinate(p.coordinate,(p.groundM+p.topM)/2);return {x:s.x+rect.x,y:s.y+rect.y,z:s.z};}).filter(p=>p.x>5&&p.x<innerWidth-5&&p.y>140&&p.y<innerHeight-160&&Math.abs(p.z)<1)};});
const before=PNG.sync.read(await page.screenshot({path:out+'/'+engine+'-'+width+'-'+mode+'.png'})).data;await page.evaluate(()=>__bridgeUpdate(false));await page.waitForFunction(()=>{__bridgeUpdate(false);return railIslandIntegration.renderer.stats.structures.vertices===0;});await page.waitForTimeout(80);const after=PNG.sync.read(await page.screenshot()).data;let pixels=0;for(const spot of detail.spots)for(let y=Math.round(spot.y)-2;y<=Math.round(spot.y)+2;y++)for(let x=Math.round(spot.x)-2;x<=Math.round(spot.x)+2;x++){const i=(y*width+x)*4;if(Math.abs(before[i]-after[i])+Math.abs(before[i+1]-after[i+1])+Math.abs(before[i+2]-after[i+2])>20)pixels++;}
rows.push({engine,width,mode,test:'只看軌道：橋面存在、橋墩接地且確實繪出',pass:detail.stats.decks>3&&detail.stats.piers>3&&!detail.overflow&&!detail.errors.length&&pixels>8,pixels,detail});console.log(engine,width,mode,rows.at(-1).pass,pixels);
await page.evaluate(()=>__bridgeUpdate());
}
// 以兩股既有高鐵股道驗雙向編組；新增結構不可更動車廂的定位與高程。
await page.evaluate(async()=>{const {makePath}=await import('./rail-3d/integration/train-path.js'),r=railIslandIntegration.renderer,ways=__bridgeFrame.routes.filter(x=>['197653374','197653373'].includes(String(x.routeId))),template=__bridgeFrame.vehicles.find(v=>v.systemId==='thsr_sched');if(ways.length!==2||!template)throw Error('缺少高鐵測例');window.__bridgeVehicles=ways.map((route,i)=>{const path=makePath(route.coordinates),s=path.locate([120.3247,23.48]).s,q=path.at(s).coordinate;return {...template,id:'bridge-direction:'+i,route,chainageM:s,longitude:q[0],latitude:q[1],railDirection:i?1:-1,followed:false};});__bridgeUpdate(true,__bridgeVehicles);});
for(const mode of ['flat','terrain']){await page.evaluate(mode=>{railIslandIntegration.renderer.setGroundMode(mode);__bridgeUpdate(true,__bridgeVehicles);},mode);await page.waitForFunction(()=>{__bridgeUpdate(true,__bridgeVehicles);return railIslandIntegration.renderer.stats.models===2;},null,{timeout:45000});const detail=await page.evaluate(()=>{const r=railIslandIntegration.renderer;return {poses:r.stats.poseSamples.map(p=>({id:p.id,cars:p.cars.length,error:Math.max(...p.cars.map(c=>Math.abs(c.height-__bridgeVehicles.find(v=>v.id===p.id).route.elevation(c.s,r.stats.groundMode)-.65)))})),fallback:r.stats.modelFallbacks,errors:r.stats.errors};});rows.push({engine,width,mode,test:'雙向高鐵列車仍貼合同一軌面',pass:detail.poses.length===2&&detail.poses.every(p=>p.cars===12&&p.error<.00001)&&!detail.fallback.length&&!detail.errors.length,detail});}
if(width===1280){await page.evaluate(()=>{railIslandIntegration.render=__bridgeRender;setSimSec(11*3600+54*60);state.playing=false;const tr=state.trains.find(tr=>tr.sys==='tra_sched'&&String(tr.train)==='114');if(!tr)throw Error('缺少114次');setFollow(tr,false,true);M.raw.jumpTo({zoom:17.5,pitch:55,bearing:50});});
for(const mode of ['flat','terrain']){await page.evaluate(mode=>railIslandIntegration.setGroundMode(mode),mode);await page.waitForFunction(()=>{const r=railIslandIntegration.renderer,id=railIslandIntegration.capture().selectedVehicleId;return r.stats.poseSamples.some(p=>p.id===id)&&r.stats.structures.decks+r.stats.structures.beds>0;},null,{timeout:45000});await page.waitForTimeout(800);const detail=await page.evaluate(()=>{const r=railIslandIntegration.renderer,f=railIslandIntegration.capture(),v=f.vehicles.find(v=>v.followed),p=r.stats.poseSamples.find(p=>p.id===v?.id);return {label:v?.publicLabel,coordinate:[v?.longitude,v?.latitude],height:p?.displayHeightM,level:p?.level,structures:structuredClone(r.stats.structures),errors:r.stats.errors};});rows.push({engine,width,mode,test:'使用者114次11:54頭前溪案例',pass:detail.label==='114'&&detail.structures.decks+detail.structures.beds>0&&!detail.errors.length,detail});await page.screenshot({path:out+'/'+engine+'-114-'+mode+'.png'});}}
rows.push({engine,width,test:'頁面無錯誤',pass:!errors.length,errors});
}catch(e){rows.push({engine,width,pass:false,error:String(e)});console.log(engine,width,e.message);}finally{await page.close();}}await browser.close();}
fs.writeFileSync(process.env.RESULT_FILE||out+'/browser.json',JSON.stringify(rows,null,2));console.log({total:rows.length,failed:rows.filter(r=>!r.pass)});if(rows.some(r=>!r.pass))process.exitCode=1;
