import fs from 'node:fs';import {chromium,webkit}from'playwright';
const base=process.env.BASE_URL||'http://127.0.0.1:5245/',rows=[];fs.mkdirSync('output/linkou',{recursive:true});
for(const [engine,type]of Object.entries({chromium,webkit})){const b=await type.launch(),p=await b.newPage({viewport:{width:1000,height:800},locale:'zh-TW'});const errors=[];p.on('pageerror',e=>errors.push(e.message));try{
await p.addInitScript(()=>localStorage.setItem('trainmap-howto-seen','1'));await p.goto(base+'?g=all&scene=3d&map=landscape&t=14:18');await p.waitForFunction(()=>state.ready&&window.railIslandPhysical&&window.railIslandIntegration?.renderer,null,{timeout:90000});await p.evaluate(()=>{state.playing=false;clearFollow();window.__frame=railIslandIntegration.capture();railIslandIntegration.render=()=>{};});
for(const [id,direction,kind]of [['198049016',1,'tunnel'],['198049017',-1,'tunnel'],['197206562',1,'tunnel'],['105198003',-1,'tunnel'],['198049018',1,'bridge'],['198049019',-1,'bridge']]){
 await p.evaluate(async({id,direction})=>{const{makePath}=await import('./rail-3d/integration/train-path.js');window.__route=railIslandPhysical.geometry.drawingWays('thsr_sched','#ee7623').find(r=>r.routeId===id);const path=makePath(__route.coordinates),s=path.length/2,q=path.at(s).coordinate,t=__frame.vehicles.find(v=>v.systemId==='thsr_sched');window.__v={...t,id:'test-linkou',route:__route,chainageM:s,longitude:q[0],latitude:q[1],railDirection:direction,followed:false};window.__update=()=>railIslandIntegration.renderer.update({...__frame,routes:[__route],vehicles:[__v],display:{...__frame.display,modelMode:'all',enabled:true},followLock:false,selectedVehicleId:null});M.raw.jumpTo({center:q,zoom:17,pitch:55,bearing:35});__update();},{id,direction});
 for(const mode of ['flat','terrain']){await p.evaluate(mode=>railIslandIntegration.setGroundMode(mode),mode);await p.waitForFunction(()=>{__update();const r=window.railIslandIntegration?.renderer;if(!r)return false;const p=r.stats.poseSamples[0];return r.stats.models===1&&p&&(r.stats.groundMode!=='terrain'||p.cars.every(c=>Number.isFinite(r.map.queryTerrainElevation(c.coordinate))&&r.map.queryTerrainElevation(c.coordinate)>30));},null,{timeout:60000});
 const detail=await p.evaluate(()=>{__update();const r=railIslandIntegration.renderer,s=r.stats.poseSamples[0];return {kind:s.level.kind,underground:s.cars.every(c=>c.underground),opaque:s.cars.every(c=>!c.underground),depth:Math.min(...s.cars.map(c=>c.height-(r.stats.groundMode==='terrain'?r.map.queryTerrainElevation(c.coordinate):0))),maxPitch:Math.max(...s.cars.map(c=>Math.abs(c.pitch))),piers:r.stats.structures.piers,models:r.stats.models,errors:r.stats.errors};});const pass=detail.kind===kind&&(kind==='tunnel'?detail.underground&&(mode==='flat'||detail.depth<-50&&detail.maxPitch<.08):detail.opaque&&detail.piers>0)&&!detail.errors.length;rows.push({engine,id,direction,mode,pass,detail});console.log(engine,id,mode,pass,pass?'':detail);if(mode==='terrain'&&['198049016','198049018'].includes(id))await p.screenshot({path:`output/linkou/${engine}-${id}.png`});
 }
}
rows.push({engine,test:'無頁面錯誤',pass:!errors.length,errors});}catch(e){rows.push({engine,pass:false,error:String(e)});}finally{await b.close();}}
fs.writeFileSync('output/linkou/results.json',JSON.stringify(rows,null,2));console.log({total:rows.length,failed:rows.filter(r=>!r.pass)});if(rows.some(r=>!r.pass))process.exitCode=1;
