// 直接檢查出貨派車表與完整來源節點走法，再用產品行車剖面驗收改動站段。
import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{restorePhysicalRoutes}from'./lib/restore_physical_routes.mjs';import{computeProfiles,readPassObs}from'./build_run_profiles.mjs';import{createPhysicalMotion,physicalTrainKey,physicalStopSignature}from'../rail-3d/physical/motion.js';import{distanceM}from'../rail-3d/integration/train-path.js';
const read=f=>JSON.parse(fs.readFileSync(f)),net=read(process.env.NETWORK||'rail-3d/physical/network.json'),dispatch=read(process.env.DISPATCH||'rail-3d/physical/dispatch.json'),proof=read('scripts/fixtures/remaining-routes-0913.json');assert.equal(crypto.createHash('sha256').update(JSON.stringify(net.ways)).digest('hex'),proof.waysSha256,'本批不得橫移或新造來源股道');for(const[k,p]of Object.entries(proof.afterPlans))assert.deepEqual(dispatch.plans[k],p,'已驗收的進路或模板保護退回 '+k);
const{g,paths}=restorePhysicalRoutes(net);for(const[id,p]of Object.entries(proof.newPaths)){assert.deepEqual(net.paths[id],p,'已驗收路徑被改寫 '+id);assert.equal(p.fromGroup,p.system+':'+(g.trackGroups.get(p.from)||p.from));assert.equal(p.toGroup,p.system+':'+(g.trackGroups.get(p.to)||p.to));}
const baseline={...dispatch,plans:{...dispatch.plans}};for(const[k,p]of Object.entries(proof.beforePlans)){if(p)baseline.plans[k]=p;else delete baseline.plans[k];}
// 「原派車表」是 2026-09-13 修復前那一份的停車節點（釘在 fixture.sourceStops），不從現行派車表倒推：後續修復（F1／F2）把別班搬走後，倒推出來的集合會少掉當時真的用過的節點。
const sourceStops=new Set(proof.sourceStops);assert(sourceStops.size>700,'原派車表停車節點集不得縮水');for(const c of proof.changes)if(c.toNode)assert(sourceStops.has(c.toNode),'不得拿未被原派車表使用的股道冒充月台');
const schedule=read('data/tra_schedule_dense.json');computeProfiles({indexPath:'index.html',schedule,track:read('data/tra.json'),passObs:readPassObs('data/tra_pass_obs.json')});const profiles=read('rail-3d/physical/display-profiles.json'),levels=read('rail-3d/physical/level-profiles.json');for(const[id,p]of Object.entries(profiles.entries))p.level=levels.entries[id];const motion=createPhysicalMotion(net,profiles,dispatch),oldMotion=createPhysicalMotion(net,profiles,baseline),changed=new Set(proof.changes.map(c=>c.key));let inherited=0,samples=0,boundaries=0,forward=0,backward=0,maxJump=0,protectedCount=0;const seen=new Set(),retimed=[];
// 同一把派車鍵在窗內有兩版時刻：台鐵 2026-10-03 起改點（官方逐日檔一路到 11/23 都是新版），406 首站樹林到站早 5 分、
// 1136／1192 在埔心早 30 秒開，起訖不變所以鍵相同。派車表一把鍵只存得下 09-13 驗收的那一版；改點版由產品以 retimed
// 沿用同一套驗收過的股道（站序、停靠型態相同，時間用今天的、不帶待避），所以照樣走下面改動車班那套檢查、照樣計入分母——
// 舊版滾出窗外之後，分母靠改點版撐住。
const retimedAtStop=(plan,tr)=>{if(!plan)return false;const was=JSON.parse(plan.stopSignature),now=JSON.parse(physicalStopSignature(tr));return was.length===now.length&&was.every((s,i)=>s[0]===now[i][0])&&tr.stops.some((s,i)=>s.stop!==false&&(was[i][1]!==now[i][1]||was[i][2]!==now[i][2]));};
// 借用模板、而模板來源正是 09-13 刻意改派的那幾班（beforePlans）⇒ 這班「跟著修法走」是預期結果，不是被動換軌；
// 不比對舊路徑，改走改動車班那套檢查（無額外 hold、道岔不倒車、進出站不跳），但不計入改動名冊分母。protectedTemplates 那幾班照舊逐條比對舊路徑，不享這個豁免。
// 起因：2026-09-18 重抓台鐵班表進來 6 班中秋加開（5xxx 次），全數借用修過的模板，舊判準把新車當成「未改車班」而紅。
for(const tr of schedule.trains){const key=physicalTrainKey(tr),r=motion.record(tr),old=oldMotion.record(tr),inh=!changed.has(key)&&!proof.protectedTemplates.includes(key)&&r?.bindingBasis==='route-template'&&r.sourceKey in proof.beforePlans;if(changed.has(key)&&retimedAtStop(dispatch.plans[key],tr)){assert.equal(r?.bindingBasis,'retimed','同鍵改點版要沿用驗收過的股道 '+key);assert.deepEqual(r.plan.pathIds,dispatch.plans[key].pathIds,'改點版不得換股道 '+key);retimed.push(tr.train);}if(inh)inherited++;if(!changed.has(key)&&!inh){if(old){assert(r,'未改車班失去綁定 '+key);assert.deepEqual(r.plan.pathIds,old.plan.pathIds,'未改車班因模板變更被動換軌 '+key);}if(proof.protectedTemplates.includes(key))protectedCount++;continue;}assert(r&&old,'改動車班必須能綁定 '+key);if(!inh)seen.add(key);assert(!r.plan.holds.some(h=>h.arrival||h.departure),'不得用額外 hold 掩蓋互穿');const ids=r.plan.pathIds;
for(let i=1;i<ids.length;i++){const a=paths[ids[i-1]],b=paths[ids[i]];assert.equal(a.to,b.from);if(old.plan.pathIds[i-1]===ids[i-1]&&old.plan.pathIds[i]===ids[i])continue;assert(g.canTurn(a.nodeIds.at(-2),a.to,b.nodeIds[1],g.edges.get(a.edgeIds.at(-1)),g.edges.get(b.edgeIds[0])),'道岔不得倒車 '+key);for(const t of[tr.stops[i].arrSec,tr.stops[i].depSec]){const p=motion.sample(tr,t-.001),q=motion.sample(tr,t+.001);if(!p||!q)continue;const jump=distanceM([p.lon,p.lat],[q.lon,q.lat]);maxJump=Math.max(maxJump,jump);assert(jump<1,'進出站跳躍 '+key);boundaries++;if(q.lat>p.lat)forward++;if(q.lat<p.lat)backward++;}}
for(const c of proof.changes.filter(c=>c.key===key)){let prev=null;for(let t=Math.ceil(c.from);t<=c.to;t++){const p=motion.sample(tr,t);if(!p)continue;assert(p.physical);for(const mode of['flat','terrain'])assert(Number.isFinite(p.route.elevation(p.chainageM,mode)));if(prev)assert(distanceM([p.lon,p.lat],[prev.lon,prev.lat])<70,'每秒位移異常 '+key);prev=p;samples++;}}
}
// protectedTemplates 的分母取「今天班表窗裡還在的那幾班」：其中 6841／6801／6835 是七堵→新烏日的專開車，
// 只在 09-09 起那個窗的特定日期跑，2026-09-18 重抓後已不在窗內，寫死 4 會讓出貨鏈隨日期浮動被擋。
assert.equal(seen.size,changed.size,'改動名冊分母不得縮水：'+[...changed].filter(k=>!seen.has(k)).join('、'));assert(forward>0&&backward>0);const liveKeys=new Set(schedule.trains.map(physicalTrainKey)),protectedLive=proof.protectedTemplates.filter(k=>liveKeys.has(k)).length;assert(protectedLive>=1,'受保護模板在今天的班表窗裡一班都不剩——這層檢查已失明，要換樣本');assert.equal(protectedCount,protectedLive);console.log({trains:seen.size,inherited,protectedLive,changes:proof.changes.length,samples,boundaries,forward,backward,maxBoundaryJumpM:maxJump,protectedCount,retimedVariants:retimed.join(' ')});
